- query_test.go
- scope_private.go
> Fix error when chaining empty where conditions

- postgres.go
> Fixed a bug that panic occurs when the value is null

- README.md
It took me a bit to figure out how to query time since there isn't any documentation on it. I thought it would be nice to have an example on the README for anybody looking to query fields like `created_at` or `updated_at`, etc.
> Add an example with time

- README.md
> Simpler (and correct) example for showing how to declare foreign keys.

- README.md
I had to look in the issues to find how to use `db.Joins` to fetch records directly, so I thought a few more examples would not hurt.
> Add examples for join.

- README.md
Add a more detailed slightly more realistic example for a transaction. This example contains error handling and transaction usage that is not reflected in the current README. Hopefully this will help others learn to how use gorm more quickly.
> Update README.md with more realistic Transaction example

- main.go
Fix errors being inaccessible due to errors being set on different *DB instance than what is returned.
> Inaccessible error fixes

- association.go
relevant issue: https://github.com/jinzhu/gorm/issues/588
> this fixes syntax error for go1.3.3

- scope_private.go
- search.go
All HAVING clauses are AND-ed together. Code modelled off whereSql(). Build passes with Sqlite3.
Resolves jinzhu/gorm#575
> Add basic support for multiple HAVING clauses.

- join_table_handler.go
- model_struct.go
- preload.go
- preload_test.go
- utils_private.go
```go
type Language struct {
Id   
Name string
Code string
}
Id    
Languages []Language `gorm:"many2many:user_languages;"`
}
users:= []User{}
db.Preload("Languages").Find(&users)
```
> ManyToMany preload

- preload.go
> Increase performance for m2m preload

- postgres.go
Check if the value is a byte array of 16 bytes and its type is named "uuid" or "guid", and if so, use postgres `uuid` type.
> add binary UUID support to postgres

- scope_private.go
> Modify count detection regex to match parenthesis instead of starting a capture.

- preload.go
When using pointers in model structs, there is an edge case.
When using preload to eagerly preload a many to many relationship and
the main row is not found by a primary key, use of reflect.Indirect in
preload.go results in a zero value and the subsequent call to
FieldByName panics the program.
Consider the following example:
```go
package somepackage
import (
"database/sql"
"github.com/jinzhu/gorm"
)
// Permission ...
type Permission struct {
gorm.Model
Name string
}
// Role ...
type Role struct {
gorm.Model
Name        string        `sql:"type:varchar(20);unique;not null"`
Permissions []*Permission `gorm:"many2many:role_permissions"`
}
// User ...
gorm.Model
RoleID        sql.NullInt64 `sql:"index;not null"`
Role          *Role
Username     sql.NullString …
```
> Fixed a bug with invalid zero value in preload

- preload.go
This change could improve Preload performance.
Related issue url: https://github.com/jinzhu/gorm/issues/860
> Issue-860. Preload performance

- documents/README.md
Fix gorm.Open dialect from 'sqlite' to 'sqlite3'
> Fix gorm.Open dialect

- callback_query_preload.go
Fixes #1008 basically the same PR as #861 but reapplied in the new preload file.
> Improved preload m2m performance

- callback_query_preload.go
> Add support for polymorphic preload

- callback_query_preload.go
- preload_test.go
I found issue in callback_query_preload. It preloads many2many relation incorect when many2many is nested model and not a pointer. Look at my code snippet to reproduce this:
``` golang
package main
import (
"github.com/jinzhu/gorm"
_ "github.com/jinzhu/gorm/dialects/postgres"
"log"
"encoding/json"
"fmt"
)
type Product struct {
gorm.Model
Name string
ShopId uint
Shop Shop
}
type Shop struct {
gorm.Model
Name string
Sellers []User `gorm:"many2many:shop_sellers;"`
}
gorm.Model
Name string
}
var tables = []interface{}{&User{}, &Shop{}, &Product{}, "shop_sellers"}
func main() {
db, err :=gorm.Open("postgres", "host=localhost user=postgres dbname=gorm_test password=1234 sslmode=disable")
if err!=nil {
log.Fatal(err)
}
defer db.Close()
db = db.Debug() …
```
> fix m2m nested preload

- main_test.go
- wercker.yml
I've set up a wercker.yml to run automated tests on mysql and postgres in addition to sqlite: https://app.wercker.com/#nkovacs/gorm/build/5740cb2c137f7fe21f0bf338
I can squash the commits if you'd like.
> Wercker postgres and mysql

- utils.go
> Fixes #1118

- main_test.go
- scope.go
Fixed a bug when joining multiple tables with the same fields and where on the same field.
> Fixed a bug when joining multiple tables with the same fields

- documents/models.md
Document DefaultTableNameHandler
> Update models.md to document DefaultTableNameHandler

- CONTRIBUTING.md
Change `db` to type `*gorm.DB` to reflect latest version of gorm.
Remove re-declarations of `db, err`
> Update CONTRIBUTING.md executable script template

- documents/development.md
> Change "GROM" to "GORM"

- query_test.go
- scope.go
> db.Raw().First() makes wrong sql fix #1214

- logger.go
When using the LogMode(true), the SQL produced during the log message…, places the bounded variables in the wrong location, this is due to the fact that the current implementation splits the values with a regex similar to: ($\d+)|?.
That works well for ? placeholders because they should be replaced in order.
However, the numeric placeholders should be replaced based on their value, for instance:
SELECT name,last FROM contact WHERE name=$2 and age=$1
Should NOT be replaced in order, because it will yield an incorrectly formed SQL command, which is not very useful for debugging.
Fixes issue: #1249
> Issue  #1249 fix - replacing $ placeholders in order when logging

- documents/advanced.md
`time.Now` is a function, it should be `time.Now()`
> fix a wrong sql

- documents/models.md
Format is broken without the three backslasees
> Add lost backslash

- main.go
Need to skip the ping, otherwise results in a nil dereference.
> Allow open to take transaction.

- logger.go
- main.go
- [] No API-breaking changes
- [] Write good commit message, try to squash your commits into a single one
Thank you.
> i think it's better,please think about it

- dialect_postgres.go
Thank you.
This pull request fixes the condition used to evaluate the postgres `uuid` type.
> Fix postgres dialect UUID sqlType evaluation

- crud.html
> fix doc pluck

- callback.go
> Use log.PrintX instead of fmt.PrintX

- dialects/postgres/postgres.go
Add a JSONB type to the postgres dialect. I'm aware of @Niondir raising an issue for this (https://github.com/jinzhu/gorm/issues/1183), but it's been nearly a year since then and as I don't see any current PRs for this so I have decided to go ahead and make a PR for it so future users of the ORM won't have to constantly reinvent this struct.
> add JSONB type

- documents/crud.md
- documents/development.md
- documents/models.md
fix typos
1. add lost double quotation in crud.md
1. add language tag on code blocks to fix code highlight
1. trim trailing space
PS: I try to run ./build.sh, it modified all the html file and search_index.json, I don't know I should commit them or not, I refer other's PR, so I just commit the markdown file, hope it's a right way.
> fix some typos in documents

- utils.go
This will fix the following issue
https://github.com/jinzhu/gorm/issues/1460
Thank you.
Fix: https://github.com/jinzhu/gorm/issues/1460
> UID should come before UI in common abbreviations

- documents/database.md
add `port=myport` in PostgreSQL connection example document.
> add port in PostgreSQL connection example

- dialect_common.go
If no database is selected, we try to guess based on the tableName.
> Use table name to guess current database if none is given

- dialects/postgres/postgres.go
Handle empty Jsonb to fix  #1649
> Add handling for empty Jsonb to fix #1649

- dialects/mssql/mssql.go
Use square brackets for quoting identifiers on MSSQL
> Use square brackets for quoting identifiers on MSSQL

- scope.go
Hello.
This is a little change to avoid problems with utf8 names on DB columns.
> Support for UTF8 names on DB

- query_test.go
> Fix typo in query_test

- main.go
> do not close wrapped *sql.DB

- main.go
- model_struct.go
- _Changes modelStructsMap implementation from map with mutex to sync.Map_
- Fixes https://github.com/jinzhu/gorm/issues/1407
> Race fix. Changes modelStructsMap implementation from map with mutex to sync.Map

- utils.go
when used go1.11 gomodules the code dir will be `$GOPATH/pkg/mod/github.com/jinzhu/gorm@*/`
fileWithLineNum check failed
- [] No API-breaking changes
> for go1.11 go mod

- callback_query_preload.go
All credits to @vanjapt who came up with this patch.
Closes #1672
It would be great if @vanjapt can help improve this PR a little bit (adding comments etc.) since I don't 100% understand the code here, but I've tested locally with production data and it seems to work correctly and sped up the `Preload`s from 7~8s to around 2s
> Improve preload speed

- scope.go
Rollback transaction when a panic happens in callback.
> Rollback transaction when a panic happens in callback

- main.go
- model_struct.go
Second part of #1407 fix as @dnathe4th reported
> Second part of the defaultTableName field race fix

- scope.go
- ~New code/logic commented & tested~
Simplifes cases of `strings.Index` with `strings.Contains`. Inspired by https://staticcheck.io/docs/gosimple#S1003
> simplify cases of strings.Index with strings.Contains

- main.go
In logMode's code, hard-coded numbers are used. This makes it a little difficult to read the gorm internal code. In this PR, I replaced them with constants.
> Make logMode code more readable

- scope.go
- [*] Do only one thing
- [*] No API-breaking changes
optimize getColumnAsArray, make association foreign primary keys unique in preload,
> optimize getColumnAsArray

- go.mod
- go.sum
> go modules

- customize_column_test.go
- model_struct.go
fixes #2322 #2326  
these two issues are the same.
> fix the table name of many2many

- callback_query_preload.go
- preload_test.go
> return empty slice for many2many if no asscociation was found

- main_test.go
Adding a test case for https://github.com/jinzhu/gorm/issues/1644
> Add test for keeping float precision

- scope.go
- scope_test.go
Closes https://github.com/jinzhu/gorm/issues/1774
> Fix drop table error with table options

- scope.go
Adds an error to the scope if there is one when beginning a transaction. Feel free to close this omission is intentional. After looking at the default create callbacks, seems like this error being ignored is potentially worrisome.
> Handle error when beginning transaction

- main.go
Comments should begin with the name of the function.
https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences
> Fix function name of comment

- callback.go
Fix typo of example code for `Replace` function in callback.go
If it's not a typo, please kindly close this PR.
> Fix typo of example code

- dialect_mysql.go
- [] No API-breaking changes
Add more description to a runtime error caused by an invalid field type
> Describe name of field for invalid SQL datatypes

- dialect_mysql.go
use mysql-only statement for get metadata
see #2642
> use show statement in mysql dialect for compatibility for tencent tdsql

- scope.go
SetColumn No fields ignored were processed
```
type Test struct {
ID        uint       `gorm:"primary_key"`
CreatedAt *time.Time `gorm:"-"`
UpdatedAt *time.Time `gorm:"-"`
}
```
Errors occur when updating records
```
pq: column "updated_at" of relation "tests" does not exist 
```
> SetColumn No fields ignored were processed

- main.go
Update will not update zero value fields , And Delete will not delete record with deleteAt filed.
I was not aware of that  until i made some bugs .
I think it is better to add some warnings to the update and delete 's comment, so people will know that more directly and quickly.
in Chinese maybe:　注意，有坑
> Add warning comment

- callback.go
- callbacks_test.go
- logger.go
> Set nopLogger to DefaultCallback for avoid nil pointer dereference

- README.md
> Replace godoc badge with pkg.go.dev

- finisher_api.go
> fix broken url

- .github/workflows/go.yml
Enable Github Action for doing unit test atomatically
> add githubAction CI for tests

- .github/labeler.yml
- .github/workflows/issue.yml
- .github/workflows/issue_stale.yml
- label if there is any playground test case
- cron run to label stale issue
- issue labler doc https://github.com/marketplace/actions/regex-issue-labeler
> add github action for issue test-case-label and stale

- association.go
- errors.go
- finisher_api.go
- statement.go
keep defined err to the same code style
> keep defined err to the same code style

- logger/sql.go
refactor function convertParams's default case
> refactor function convertParams's default case

- tests/scanner_valuer_test.go
- [] Tested
Add test case https://github.com/go-gorm/gorm/issues/3248#issuecomment-671165845
> add testcase

- chainable_api.go
> fix order case

- clause/expression.go
- tests/query_test.go
> correct generated sql

- soft_delete.go
https://github.com/go-gorm/gorm/issues/3693
- [] Tested
Marshaling zero-valued Deleted at to null
> Marshaling zero valued DeletedAt to null

- clause/expression.go
Simplify the writing instead of using struct literal.
> refactor: simplify the writing instead of using struct literal

- schema/schema.go
I was reading the latest release diff and noticed an issue with schema initialization. I split this PR into two commits: the first fixes bugs and the second rearranges code to be less deeply nested.
The initialized channel was only closed if the schema's cacheStore did not contain the embeddedCacheKey and there were no errors parsing relations.  If the key existed or an error occurred, it would not be closed. This could leave other goroutines waiting for synchronization that will never occur.
Additionally, the other goroutines that wait for initialization to complete did not return the possible error.
> Fix schema initialization paths

- gorm.go
> reduce DB's Use method complexity and make it easier to understand

- .github/workflows/tests.yml
Fix typo in tests.yml workflow
N/A
> Fix typo in tests.yml

- callbacks.go
- scan.go
- tests/scan_test.go
retrieving gorm object support pointer
implement feature described in https://github.com/go-gorm/gorm/issues/4003 issue.
``` go
var user *User
// 获取第一条记录（主键升序）
db.First(&user)
// SELECT * FROM users ORDER BY id LIMIT 1;
// 获取一条记录，没有指定排序字段
db.Take(&user)
// SELECT * FROM users LIMIT 1;
// 获取最后一条记录（主键降序）
db.Last(&user)
```
> retrieving gorm object support pointer

- association.go
- callbacks.go
- errors.go
- gorm.go
invalid db error
invalid value and invalid value length error
> invalid db error and value and invalid value length error refactor.

- migrator/migrator.go
optimize migrate column regexp
> optimize MigrateColumn method for regexp

- migrator/migrator.go
continue https://github.com/go-gorm/gorm/pull/4028
> Respect ignore migration when add column

- schema/field.go
Optimal value type acquisition for schema/field.go#481
> Optimal value type acquisition for v

- callbacks/associations.go
- callbacks/helper.go
- migrator/migrator.go
- schema/field.go
- schema/utils.go
- statement.go
1.feat: optimize relect value length and value
2.feat: optimize ConvertSliceOfMapToValuesForCreate method
> Optimize reflect value length and method

- logger/logger.go
simplify defaultLogger's Trace if depth
> slim trace if depth

- schema/schema.go
Optimizing the `func Parse(dest interface{}, cacheStore *sync.Map, namer Namer) (*Schema, error)` function in schema.
Store schema in advance to prevent other goroutines from generating schema repeatedly.
> Optimizing the parse function in schema

- schema/relationship.go
- [] Non-breaking API changes
- [] Tested
fixes English grammar in an error message
> Small grammar fix in error message

- tests/associations_test.go
- [] Tested
Fixed typo.
occured -> occurred
> Fix typo in associations_test.go

- statement.go
> golint standard

- finisher_api.go
> Fix Pluck's usage #4473

- schema/schema.go
This PR will fix wrong callback warning.
> slightly better callback warning

- clause/select.go
- clause/select_test.go
add comma expression which produces expressions separated by commas when Build called
```golang
clause.CommaExpression{
[]clause.Expression{
clause.NamedExpr{"?", []interface{}{clause.Column{Name: "id"}}},
clause.NamedExpr{"?", []interface{}{clause.Column{Name: "name"}}},
clause.NamedExpr{"LENGTH(?)", []interface{}{clause.Column{Name: "mobile"}}},
},
}
// represents: 
//`id`, `name`, LENGTH(`mobile`) 
```
> New Comma Expression

- migrator/migrator.go
- tests/migrate_test.go
Fix create index with comments in MySQL.
https://dev.mysql.com/doc/refman/8.0/en/create-table.html
https://dev.mysql.com/doc/refman/8.0/en/create-index.html
https://gorm.io/docs/indexes.html#Index-Tag
> Fix create index with comments in MySQL

- schema/field.go
optimize setupValuerAndSetter func for fallbackSetter func on field.FieldType.Elem()
> optimize setupValuerAndSetter func

- callbacks/helper.go
update comment for ConvertSliceOfMapToValuesForCreate func
> update comment for ConvertSliceOfMapToValuesForCreate func

- schema/schema.go
optimize Parse func for fieldValue.Interface
> optimize Parse func for fieldValue.Interface

- migrator/migrator.go
optimize migrator.go MigrateColumn and ColumnTypes func.
> optimize migrator.go MigrateColumn and ColumnTypes func.

- .github/dependabot.yml
- .github/workflows/invalid_question.yml
- .github/workflows/missing_playground.yml
- .github/workflows/reviewdog.yml
- .github/workflows/stale.yml
- tests/go.mod
This pr upgrades the go and github-actions dependencies with Dependabot help. 
The dependabot.yml file allows you to configure how frequently the bot is checking the dependencies. The documentation is here https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates 
Keep dependencies up-to-date
> Update Dependencies 

- chainable_api.go
- tests/table_test.go
> fix: table couln't be reentrant

- logger/logger.go
This change can improve readability of code as setting  all fields of Config for Default Logger explicitly.
None
> chore(logger): explicitly set config of Default Logger

- finisher_api.go
> feat: count accpet `db`.`table`

- .github/workflows/tests.yml
> Add Go 1.17

- clause/expression_test.go
- statement.go
> fix: QuoteTo not fully support raw mode

- callbacks/transaction.go
- finisher_api.go
- [] Tested
Pr for https://github.com/go-gorm/gorm/issues/4818
```
func TestGORM(t *testing.T) {
DB.Table("non_existent").WithContext(context.Background()).FirstOrCreate(&User{Name: "foo"})
DB.Table("non_existent").WithContext(context.Background()).FirstOrCreate(&User{Name: "foo"})
DB.Table("non_existent").WithContext(context.Background()).FirstOrCreate(&User{Name: "foo"})
connPool := DB.ConnPool.(*sql.DB)
v := reflect.ValueOf(connPool).Elem()
f := v.FieldByName("numOpen")
if f.Int() > 1 {
t.Errorf("Expected open one connections but found %d", f.Int())
}
}
```
result：
```
--- PASS: TestGORM (0.00s)
PASS
```
> fix connections leak

- callbacks/create.go
- callbacks/delete.go
- callbacks/preload.go
I think the readability of the code is more important. The unnecessary if...else can be completely removed. At the same time, the processing of err should be processed as early as possible, so that the logic can be read coherently, clearly and clearly, and it can also enhance the maintainability of the code. And expandability.
> Refactor if logic

- .github/workflows/reviewdog.yml
- clause/expression.go
- statement.go
- tests/go.mod
- tests/postgres_test.go
- [*] Do only one thing
- [*] Non breaking API changes
- [*] Tested
> Add unused argument

- callbacks/associations.go
- callbacks/create.go
- callbacks/delete.go
- callbacks/preload.go
- callbacks/raw.go
- callbacks/row.go
- callbacks/transaction.go
- callbacks/update.go
- migrator/migrator.go
- scan.go
1.go code style adjust for callbacks package
2.optimize code logic for callbacks package
> feat: go code style adjust and optimize code for callbacks package

- finisher_api.go
- tests/count_test.go
- tests/go.mod
> fix: count() when use group by and only find one record

- callbacks/create.go
- callbacks/delete.go
- callbacks/query.go
- callbacks/update.go
- soft_delete.go
- tests/update_test.go
> fix: save not use soft_delete

- tests/tests_test.go
> improve the error handle in tests_test

- errors.go
- finisher_api.go
- tests/count_test.go
https://github.com/go-gorm/gorm/pull/4833#issuecomment-961566529
> preoload not allowd before count

- finisher_api.go
Added comments to describe FirstOrInit and FirstOrCreate methods.
This PR will add comments to existing methods for better description
Added comments for more visibility
> Added comments to existing methods

- logger/sql.go
> fix: isPrintable incorrect

- association.go
- callbacks/associations.go
- callbacks/create.go
- callbacks/delete.go
- callbacks/preload.go
- callbacks/query.go
- callbacks/update.go
- finisher_api.go
- gorm.go
- interfaces.go
- migrator/migrator.go
- scan.go
- schema/field.go
- schema/field_test.go
- schema/interfaces.go
- schema/pool.go
- schema/relationship.go
- schema/schema_helper_test.go
- schema/serializer.go
- schema/utils.go
- soft_delete.go
- statement.go
- tests/create_test.go
- tests/go.mod
- tests/serializer_test.go
- utils/utils.go
> Add serializer support

- migrator.go
- migrator/column_type.go
- migrator/migrator.go
- tests/go.mod
- tests/migrate_test.go
> Column type interface

- association.go
- callbacks/associations.go
- callbacks/create.go
- callbacks/delete.go
- callbacks/preload.go
- callbacks/query.go
- callbacks/update.go
- finisher_api.go
- interfaces.go
- migrator.go
- migrator/column_type.go
- migrator/migrator.go
- scan.go
- schema/field.go
- schema/field_test.go
- schema/interfaces.go
- schema/pool.go
- schema/relationship.go
- schema/schema_helper_test.go
- schema/serializer.go
- schema/utils.go
- soft_delete.go
- statement.go
- tests/create_test.go
- tests/go.mod
- tests/migrate_test.go
- tests/serializer_test.go
- utils/utils.go
> Add Serializer, Update migrator ColumnType interface

- logger/sql.go
- logger/sql_test.go
- schema/naming.go
- tests/sql_builder_test.go
> style: use ReplaceAll instead of Replace

- gorm.go
> fix variable shadowing

- association.go
> fix: context missing in association

- finisher_api.go
> unify db receiver name

- finisher_api.go
- tests/create_test.go
> fix: FirstOrCreate RowsAffected

- callbacks/helper.go
> fix spelling mistake

- statement.go
- tests/hooks_test.go
`Statement.Changed()` behavior should be same when using map and struct.
```go
// tx.Statement.Changed("Code") => true
DB.Model(&product).Select("Name", "Code", "Price").Updates(map[string]interface{}{"Name": "Product New4", "code": ""})
// tx.Statement.Changed("Code") => false
DB.Model(&product).Select("Name", "Code", "Price").Updates(Product3{Name: "Product New4", Code: ""})
```
> fix: stmt.Changed zero value filed behavior

- schema/field.go
> check for pointer to pointer value

- tests/migrate_test.go
test for https://github.com/go-gorm/postgres/pull/98
> test: test for postgrs serial column

- tests/migrate_test.go
fix: add judge result of AutoMigrate
judge result of AutoMigrate , See if it has an error, show error if has
> fix: add judge result of auto_migrate

- callbacks/query.go
- tests/hooks_test.go
> fix: preload with skip hooks

- finisher_api.go
- tests/transaction_test.go
> fix: trx in hooks clone stmt

- tests/migrate_test.go
test for https://github.com/go-gorm/postgres/pull/115
> test: pg array type

- association.go
- tests/associations_test.go
> fix empty QueryClauses in association (#5502)

- schema/field.go
- tests/embedded_struct_test.go
> fix: embedded default value

- schema/schema.go
> Fixed some typos in the code comment

- utils/tests/models.go
Check the gorm tag  by https://github.com/a631807682/tagcheck and find the following warning
> tagcheck -tests ./...
```log
utils/tests/models.go:67:36: not support Gorm option "amount_off" (STC1001)
utils/tests/models.go:68:36: not support Gorm option "percent_off" (STC1001)
```
> chore: fix gorm tag

- gorm.go
> fix: correct grammar

- tests/postgres_test.go
CI failed by https://github.com/go-gorm/postgres/pull/121 , autoincrement tag is unnecessary.
> test: remove uuid autoincrement tag

- scan.go
Optimize code logic `func (db *DB) scanIntoStruct(rows Rows, reflectValue reflect.Value, values []interface{}, fields []*schema.Field, joinFields [][2]*schema.Field)`
NONE
> Optimize: code logic db.scanIntoStruct()

- callbacks/update.go
> fix: update omit

- scan.go
support scan assign slice cap，instead of the default cap of 20
for example:
```go
users := make([]User, 0, 2)
db.Where(...).Find(&users).Error
```
the initial make cap is 2, instead of 20
> support scan assign slice cap

- schema/relationship.go
- tests/callbacks_test.go
- tests/transaction_test.go
> fix maybe nil panic

- callbacks/query.go
- chainable_api.go
- statement.go
- tests/joins_test.go
> fix(Joins): args with select and omit

- .golangci.yml
> feat: golangci add goimports and whitespace

- README.md
> doc(README.md): add contributors

- gorm.go
- prepare_stmt.go
> cleanup(prepare_stmt.go): unnecessary map delete

- finisher_api.go
The grammar becomes clearer
FirstOrCreate The grammar becomes clearer
remove the invalid default s
> clear code syntax

- migrator/migrator.go
- tests/migrate_test.go
> fix:Issue migrating field with CURRENT_TIMESTAMP

- schema/index.go
- schema/index_test.go
> fix(schema): field is only unique when there is one unique index

- callbacks/row.go
- errors.go
- statement.go
- tests/query_test.go
> fix:throw model value required error

- chainable_api.go
> fix: miss join type

- tests/migrate_test.go
refer to https://github.com/go-gorm/postgres/pull/157
> test: pgsql migrate unique index

- tests/query_test.go
Remove redundant code in test
> N/A
> Refactor: Remove redundant code

- callbacks/create.go
- tests/create_test.go
> fix: on confilct with default null

- tests/migrate_test.go
> test: pgsql alter column from smallint or string to boolean

- chainable_api.go
comment example
db.Table("users").take(&result) -> db.Table("users").**T**ake(&result)
> fix typo in comment example of DB.Table()

- callbacks/query.go
- tests/joins_test.go
https://github.com/go-gorm/gorm/issues/5280#issuecomment-1521096450
> fix: nested joins alias

- schema/utils.go
- [ x ] Do only one thing
- [ x ] Non breaking API changes
- [ x ] Tested
我的使用场景遇到了 类型为 interface 的问题
使用 reflect 构建的 model 对象在 Find 中 Preload 失效
https://github.com/go-gorm/gorm/issues/6416
> fix schema GetIdentityFieldValuesMap interface or ptr

- tests/embedded_struct_test.go
Migration error caused by nested user containing its own relational table.
relate to https://github.com/go-gorm/gorm/pull/6579
> test: fix TestEmbeddedRelations

- schema/schema_helper_test.go
- schema/schema_test.go
resolve implicit memory aliasing in for loop,in the following files:
schema\schema_helper_test.go:167	                                
schema\schema_test.go:50
schema\schema_test.go:140
> refactor: Resolve implicit memory aliasing in for loop

- utils/utils.go
- utils/utils_test.go
Fixes issue #6016.
It panics on prepare request stage in some rare cases
> Fix: panic on nullable value with multiple foreign key usage

- tests/create_test.go
- tests/migrate_test.go
> fix some typos in tests

- schema/constraint.go
> chore: optimize `regEnLetterAndMidline` regular

- prepare_stmt.go
for https://github.com/go-gorm/gorm/issues/6922
support prepare stmt ping
> feat: prepare_stmt support ping

- callbacks/preload.go
- tests/preload_test.go
> perf: merge nested preload query when using join

- clause/where.go
- clause/where_test.go
- tests/query_test.go
> fix: not clause with or condition

- chainable_api.go
chainable order support clause.OrderBy
see code comment
> feat: chainable order support clause.OrderBy

- logger/logger.go
See issue https://github.com/go-gorm/gorm/issues/7336
> Enhance db.Scan with ParamsFilter - Issue 7336 - Suggestion

- .github/workflows/tests.yml
- tests/tests_test.go
mssql ci failed 
https://github.com/microsoft/mssql-docker/issues/895
> test: mssql ci

- schema/field.go
A little optimization for filed.ValueOf
> A little optimization for filed.ValueOf

- gorm.go
> Call after initialize for gorm.Config

- schema/field.go
Another commit for https://github.com/go-gorm/gorm/pull/7526.
Sorry, this commit was not pushed for network reasons, I just noticed today.
> optimize: field.ReflectValueOf

- tests/compose.yml
…ccessfully.
Update the docker compose file to make /Tests/tests_all.sh can run successfully.
> Update the docker compose file

- chainable_api.go
- finisher_api.go
- utils/utils.go
- utils/utils_test.go
The function name was misleading, as it returned true for invalid characters.
> Rename IsValidDBNameChar to IsInvalidDBNameChar
