go-gorm/gorm

utils_private.go

Hey @jinzhu (and community!) - thanks for the excellent work.  I found an issue where scope.Updates() weren't ignoring fields that had been tagged `sql:"-"` and tracked it down to this.  Note that while I was digging, I also found this introduction from a while ago: https://github.com/jinzhu/gorm/commit/c3d2746912d9e16af54b75e2baefca87ae7990cc#diff-ee3fac9069b0a4978ec2ce9e09640bf7R103 that appears to be no-op?  Was there another way that ignored fields where supposed to be ignored that was never completely implemented / is that a better solution?
thanks!

check isIgnored when compiling attrs to update

---

postgres.go

Ensure identifiers are quoted for `RETURNING` and `DROP INDEX` statements.
Before:
INSERT INTO "public_key" ("key","sha256","md5","created_at")
VALUES ('{{something}}','2015-01-13 15:09:43.866500097 -0800 PST')
RETURNING public_key.id
Error:
pq: Function id is not defined
After:
INSERT INTO "public_key" ("key","sha256","md5","created_at")
VALUES ('{{something}}','2015-01-13 15:09:43.866500097 -0800 PST')
RETURNING "public_key"."id"

Ensure identifiers are quoted for `RETURNING` and `DROP INDEX` statements.

---

scope.go
slice_test.go

I've got a list type that I want to serialise to a single value (included below). With this change, gorm will check to see if a slice can be treated as a value, just as happens with structs below. The column in the database is like `create table x (identifiers jsonb[])`.
```go
type Identifier struct {
Use      Code          `json:"use"`
Label    string        `json:"label"`
System   URI           `json:"system"`
Value    string        `json:"value"`
Period   *Period       `json:"period"`
Assigner *Organization `json:"assigner"`
}
type IdentifierList []Identifier
func (i IdentifierList) Value() (driver.Value, error) {
bits := []string{}
for _, v := range i {
if d, err := json.Marshal(v); err != nil {
return nil, err
} else {
bits = append(bits, strconv.Quote(string(d)))
}
}
v := []byte("{" …
```

check for IsScanner on slices

---

README.md
main.go
scope_private.go

Add ability for adding foreignkey and update readme
```
// 1st    fieldname
// 2nd    destination table(id)
// 3rd    ONDELETE
// 4th    ONUPDATE
db.Model(&Post{}).AddForeignKey("category_id", "categories(id)", "CASCADE", "CASCADE")
```
This is a re-submitted pull request #359 , but with different branch (#359 was on master branch)

Add Scope.addForeignKey()

---

scope_private.go

Previously, specifying a struct like:
type Foo struct {
Email        string    `sql:"unique_index:idx_email_agent"`
UserAgent    string    `sql:"unique_index:idx_email_agent"`
}
…would result in an `idx_email_agent` index created over `user_agent`, excluding `email`.

Fix creation of composite unique indexes

---

README.md

`OwnerType` is either `"Cat"` or `"Dog"` in this example, so the actual type should be `string`

Fix type of OwnerType in polymorphism example

---

README.md
callback_shared.go
main.go
scope.go
update_test.go

Yesterday I noticed that when invoking `UpdateColumns(...)` it would try to save all associated records.  I found this to be highly undesirable and it seemed like only an `UPDATE ...` statement should have been run.
This patch achieves the desired effect for at `UpdateColumns(...)`.
Relevant unit-test is included.
=== RUN TestUpdateColumnsSkipsAssociations
--- PASS: TestUpdateColumnsSkipsAssociations (0.10s)
PASS
All unit tests:
ok  	github.com/jinzhu/gorm	2.576s

Skip saving associations during UpdateColumns(...)

---

README.md
dialect.go
foundation.go
join_table_handler.go
main.go
main_test.go
scope_private.go
test_all.sh

This is now ready for review.
For "test_all.sh", at first I wasn't sure about adding foundation, but ultimately I figured it was best to include it.
One interesting lesson I learned while implementing this dialect is that the FoundationDB `DATETIME` type does not support timezones.
The unit-tests are passing for me, he is the output:
jay@jays-mba:~/go/src/github.com/jinzhu/gorm$ ./test_all.sh
testing postgres...
=== RUN TestRegisterCallback
--- PASS: TestRegisterCallback (0.00s)
=== RUN TestRegisterCallbackWithOrder
--- PASS: TestRegisterCallbackWithOrder (0.00s)
=== RUN TestRegisterCallbackWithComplexOrder
--- PASS: TestRegisterCallbackWithComplexOrder (0.00s)
=== RUN TestReplaceCallback
[info] replacing callback `create` from /Users/jay/go/src/github.com/jinzhu/gorm/callback_test.go:94 …

FoundationDB dialect integration

---

scope.go

in `callback_create.go`,  there is a callback to set CreatedAt and UdpatedAt
```
func UpdateTimeStampWhenCreate(scope *Scope) {
if !scope.HasError() {
now := NowFunc()
scope.SetColumn("CreatedAt", now)
scope.SetColumn("UpdatedAt", now)
}
}
```
but if specified a different database column name, like this : 
```
CreatedAt    time.Time  `gorm:"column:page_created"`
UpdatedAt    time.Time  `gorm:"column:page_updated"`
```
the SetColumn wont set the CreateAt field correctly, this PullRequest will fix this.

look up the Field.Name in Scope.SetColumn

---

callback_query.go

Postgresql requires certain column names to be quoted.
When unquoted, all upper-case characters will be converted to lower-case,
and column names like 'typeID' will result in a query on 'typeid', which will fail the query.

Quote the primary column name when doing queries

---

scope_private.go

Ignored (non-blank) fields still show up in the SQL, with an empty column name. This causes an error in Postgres, but strangely not in SQLite.
Consider:
```go
Id      int64
Name    string
Ignored string `sql:"-"`
}
u := User{
Name:    "bob",
Ignored: "some_value",
}
var r User
// SQL: SELECT  * FROM "users"  WHERE ("name" = 'bob') AND ("" = 'some_value') ORDER BY "users"."id" ASC LIMIT 1
if err := db.First(&r, &u).Error; err != nil {
t.Fatal(err) // ERROR: zero-length delimited identifier at or near """"
}
```

Fix including ignored field in Where condition

---

doc/development.md

Changed it to point to `callback_query.go` instead of `callback_create.go`.

Fixed the "Query callbacks" URL.

---

preload.go

This fixes the issue when preloading .Preload("Project.Repositories").Find(&[]User{})
with 
Project *Project
}
type Project struct {
Repositories []Repository
}
type Repository struct {
...
}

Support for preload of Struct Ptr

---

callback_create.go

This fixes a panic when err it not nil and result is nil, but error is still not reported by Create.

Fix Create when dialect does not support last inserted id

---

README.md

This should clarify the use of the transaction database handle in general.
The example following does give a very good specific example.

Provide clear explanation of transaction database handle

---

scope_private.go

Added missing field name quoting for `ALTER TABLE' and `CREATE INDEX' statements.

Added missing field name quoting for DDL statements

---

scope.go

Surface errors emitted by "'`'"RowsAffected'.

Surface errors emitted by `RowsAffected'.

---

common_dialect.go

Fix panic in function databaseName when there are special characters in password, such as '?', '/'.

fix panic in function databaseName()

---

README.md
main.go
scope_private.go

Hi all,
I've forked jinzhu/gorm more than a year ago, and did modify the code at that time to provide another mysql engine. For instance, the goal was to create tables with InnoDB engine without changing the default storage engine. It's time to share the code if some of you find some interest.
Code is pretty simple, but I did create a new function to distinguish the regular Open and the version with table options, called "OpenWithTableSuffix". Looking at latest syntax, https://dev.mysql.com/doc/refman/5.7/en/create-table.html, it exists several table options. Engine is one of the many possibilities. 
Best regards,
Gabriel

Table suffix to create tables with InnoDB engine

---

common_dialect.go
dialect.go
foundation.go
main.go
mssql.go
mysql.go
postgres.go
query_test.go
sqlite3.go

I've found this functionality to be very useful in my own projects to avoid hardcoding database names.
I took the time to add support for all dialects and add a corresponding unit-test.

`CurrentDatabase' implementation.

---

common_dialect.go
ddl_errors_test.go
delete_test.go
foundation.go
main.go
main_test.go
mssql.go
mysql.go
postgres.go
sqlite3.go

Ensure DDL dialect queries propagate error states to descendent scopes.
Includes relevant unit-test.
Branched from jay/current_database (please merge that branch first!).

Ensure DDL dialect queries propagate errors back to descendent scopes.

---

logger.go

This allows reuse of the nice formatting done by gorm while still sending the output to a custom logger.
For my use case it allowed easy integration with the glog library with a simple wrapper:
type LogWrapper struct{}
func (l *LogWrapper) Println(v ...interface{}) {
glog.Info(v)
}
and then something like:
`d.SetLogger(gorm.Logger{&LogWrapper{}})`

Change logger to use an interface.

---

scope_private.go

if buildSelectQuery() is executed twice, then we get more values in SqlVars than expected

do not execute buildSelectQuery twice

---

scope_private.go
sqlite3.go

Omit the "PRIMARY KEY" clause at the end of the create statement if
any column's SQL tags already contains the PRIMARY KEY constraint.
SQLite requires the AUTOINCREMENT keyword to be specified on columns
with an INTEGER type and a PRIMARY KEY constraint: 
https://www.sqlite.org/autoinc.html.

Support the AUTOINCREMENT keyword on SQLite.

---

main.go

*DB is cloned, we should ALWAYS use the cloned pointer instead of original one.

Fix FirstOrXXX access invalid memory address

---

query_test.go
scope_private.go

Bug: Where condition when primary key is String and the query value start with zeros. For example: 
```go
type AddressByZipCode struct {
ZipCode    string    `gorm:"primary_key:yes"`
Address    string
}
```
When I search for a Address with `ZipCode = "00501"`:
```go
DB.First(&address, "00501")
```
The built SQL query with WHERE condition is:
```sql
SELECT  * FROM "address_by_zip_codes"  WHERE ("zip_code" = '501') ORDER BY "address_by_zip_codes"."zip_code" ASC LIMIT 1
```
But the correct query is:
```sql
SELECT  * FROM "address_by_zip_codes"  WHERE ("zip_code" = '00501') ORDER BY "address_by_zip_codes"."zip_code" ASC LIMIT 1
```

Fix where clause for string primary key when query value is numeric and starts with zero

---

README.md

Just a small fix I have seen while reading through the docs.

Fixed Typo in Default values Section

---

sqlite3.go

Handle table definitions like ", \"col"" and ",col".
Fix: #459

sqlite3: fix HasColumn - problem with detecting columns

---

postgres.go

Before https://github.com/jinzhu/gorm/commit/3cb95264dff572434ed72977d78f16ab4fe1dc83,
SqlTag() returns "bytea" for []byte FIeld with no tag.
For example,
```
type Model struct {
Field [] byte
}
```
After https://github.com/jinzhu/gorm/commit/3cb95264dff572434ed72977d78f16ab4fe1dc83,
SqlTag() returns error if not specifying explicit tag.

Fix SqlTag() in case of ByteSlice

---

postgres.go

this PR #706 broken another case
Example: 
EncryptedPassword []byte  `json:"-" sql:"encrypted_password;not null"`

Break [] byte, I was breaking another case

---

postgres.go

value with value.Kind() == reflect.Slice does not have value.Type().Len()
#708 is incomplate fix. I'm sorry.

Fix panic() in isUUID()

---

model_struct.go

@jinzhu 
Thank you always for this useful library. It's very helpful for daily work and also my private work.
These days, I faced to data model with `ID` field (it is `ID` actually, semantically) but it's not-zero-origin  and not-sequential.
I want to name this field `ID` but not want to be auto-incremental.
I found your code is already extensible enough! So I modified `generateSqlTag` func a bit. In this pull-request, I use `NO` for adhoc spell, but it's just an idea.
Please tell me your idea, or I'm very glad if you merge this request. 
Thank you
----

Enable to decline antuincrement on ID field

---

field.go

provide user with information about which field can't be converted and the types involved

provide user with more descriptive error message

---

preload.go
preload_test.go

This was actually broken with the refactoring. I added a test to catch the other place the error was occurring. See the new `TestManyToManyPreloadForNestedPointer` test in preload_test.go.
See the issue also happens when there is one to one relationship on top of many to many relationship. For example:
```go
type (
Level1 struct {
ID    uint
Value string
}
Level2 struct {
ID      uint
Value   string
Level1s []*Level1 `gorm:"many2many:levels;"`
}
Level3 struct {
ID       uint
Value    string
Level2ID sql.NullInt64
Level2   *Level2
}
)
```
And then doing:
```go
Preload("Level2.Level1s")
```

There was still an issue with preloading and pointers.

---

README.md

made the paragraph about transactions in callbacks more straightforward

clean up wording in README

---

model_struct.go

There was a data race caused by the copy of the ModelStruct. See #723.
Fixes #723.

Give (*ModelStruct).TableName() a pointer receiver

---

scope.go

db.Commit() will return error but it is ignored.
We find this problem in this issue https://github.com/pingcap/tidb/issues/822.

scope: Catch error for db.Commit()

---

scope_private.go

Fixes wrong number of args for format in Sprintf call bug in addForeignKey function
```
pq: constraint "share_reports_share_id_shares_foreign_extra_string_" for relation "share_reports" already exists
```
Got unexpected constraint foreign key name `share_reports_share_id_shares_foreign_extra_string_`, want `share_reports_share_id_shares_foreign`.

Fixes unexpected keyname bug in addForeignKey function

---

polymorphic_test.go

One assertion comment says look for association with dog but the code
still uses cat. This aligns the code to now look at the association of
the dog.

Fix polymorphic test

---

query_test.go
scope_private.go

Previously, querying with an inline map created 'where conditions' which always used the equality operator for comparison. This is problematic when trying to compare find records which are `NULL`.
This changes the inline map query build condition to use `IS NULL` instead of the equality operator when the provided value is `nil`. The inverse `NOT` has also been update to produce an `IS NOT NULL` condition.

Fixes querying with inline map when a value is nil

---

preload.go
preload_test.go

There is an issue with preload functionality where FieldByName causes panic when your models are structured in a certain way.
It happens when doing a nested preload when some objects have relations you are trying to preload but some don't.
Here is an example script which causes panic.
This line fails:
`db.Preload("UserProfiles.Profile")`
```go
package main
import (
"database/sql"
"log"
_ "github.com/go-sql-driver/mysql"
"github.com/jinzhu/gorm"
_ "github.com/lib/pq"
_ "github.com/mattn/go-sqlite3"
)
var db gorm.DB
// Profile ...
type Profile struct {
gorm.Model
Name string `sql:"type:varchar(40);not null"`
}
// User ...
gorm.Model
Username     string `sql:"type:varchar(100);not null;unique"`
UserProfiles []*UserProfile
}
// UserProfile ...
type UserProfile struct { …
```

Fixed an issue with reflect.Value.FieldByName causing panic

---

README.md

Fix a minor typo when showing Related usage with field name omit, so it doesn't confuse new users.

Fix README typo on Related usage.

---

README.md

Hi,
One of your Count function examples causes a panic for me on Go 1.5.3. For example:
```go
a.db.Find(Sms{}).Count(&count)
```
Changing this to a pointer to the struct fixes the problem:
```go
a.db.Find(&Sms{}).Count(&count)
```
This PR updates the documentation to show a pointer to the struct instead.

Fix documentation for Count() function example

---

preload.go
preload_test.go

Fix the following reflection panic when using nested preload:
```
➜  gorm git:(master) ✗ go test -test.v -test.run TestNestedManyToManyPreload3
testing sqlite3...
(no such table: animals) 
[2016-02-04 21:12:10]  
(no such table: users) 
[2016-02-04 21:12:10]  
=== RUN   TestNestedManyToManyPreload3
--- FAIL: TestNestedManyToManyPreload3 (0.06s)
panic: reflect: call of reflect.Value.FieldByName on ptr Value [recovered]
panic: reflect: call of reflect.Value.FieldByName on ptr Value
goroutine 21 [running]:
testing.tRunner.func1(0xc82012f0e0)
/usr/local/go/src/testing/testing.go:450 +0x171
reflect.flag.mustBe(0xd6, 0x19)
/usr/local/go/src/reflect/value.go:199 +0xa6
reflect.Value.FieldByName(0x868660, 0xc8204eaf78, 0xd6, 0x99e580, 0x7, 0x0, 0x0, 0x0)
/usr/local/go/src/reflect/value.go:788 …
```

Fix a reflection panic with nested preloads

---

preload.go
preload_test.go

Fixed another nested preload bug I encountered.
There might be more bugs similar to this one, basically every time you try to do:
```
object.FieldByName
```
You should first check if `object` is a pointer:
```
if object.Kind() == reflect.Ptr {
object = object.Elem()
}
```
I have also refactored a test from my previous PR a bit.

Fixed a nested preload panic bug.

---

main_test.go
scope.go

Before, only HasTable(&Foo) would work but HasTable("foos") would always
return false. This PR fixes that.

HasTable now works with table name passed as a string.

---

scope_private.go

The hasCountRegexp and check in the selectSql was causing issues on queries with embedded count(*) in them.  For example, a query in the following format will fail to act as expected -
db.Table("table1").Select("*, (select count(*) from table2 where table1.id = table2.id)").Order("table1.name")
The sql generated will not include the order by clause, but will also not generate any errors.
The new behavior is that the query will attempt to run exactly as the developer entered it - if it is invalid, the developer will receive an error.  If the developer uses the built in gorm Count() method, any order by clauses will be ignored, and the correct count will be returned.

Remove regex guess on counting query

---

documents/README.md

The GORM Getting Started guide has a helpful code example. However, the example lacks initial schema migration and when run for the first time will error out with 
```
(no such table: products) 
[2016-04-29 11:54:09]  
(no such table: products) 
[2016-04-29 11:54:09]  
(no such table: products) 
[2016-04-29 11:54:09]  
(no such table: products) 
[2016-04-29 11:54:09]  
```
The proposed change resolves the error and ensures that the Getting Started example will successfully read from and write to the database.

Consider migrating schema in Getting Started Guide

---

callback_create.go

This commit closes #979 by fixing the post-insert SELECT call

Properly quotes column names in post-insert SELECT

---

association.go

Prevents panics if associations are used as described in the docs but an error happened beforehand. (Like missing ID or something since the model wasn't saved yet.)
Not in `(a *Association) Count() int` since, well, int. Ideas? Why does this work differently then the other `Count()`s anyway? (Returning an int instead of writing to a pointer)

association: dont execute Append/Replace/Delete if Error already present

---

association_test.go
dialect.go
dialect_common.go
dialect_mysql.go
dialects/mssql/mssql.go
migration_test.go
scope.go

This is based on #947, but it doesn't add a new method, it automatically hashes the key name if it would be too long on mysql.
I had to add a new method to Dialect to make the foreign key name different for mysql.

Mysql foreign key length fix

---

association_test.go
dialect_mysql.go
migration_test.go

This fixes a panic introduced in #1029 and makes the character length calculation use utf8 runes, because that's what MySQL uses (["You can use multibyte characters without reducing the number of characters permitted for values stored in these columns."](http://dev.mysql.com/doc/refman/5.7/en/identifiers.html)).

fix panic in AddForeignKey on mysql dialect

---

callback_query_preload.go
preload_test.go

I have encountered a possible panic while preloading non existent fields (e.g. a foreign key can be NULL).
Check the unit tests. Uncomment my bugfix in `callback_query_preload.go` and run the tests to verify the bug. You will get a panic because `currentScope.getColumnAsScope` can possibly return nil pointer and you don not check for that case currently.

Fixed an occurrence of a panic while preloading non existent fields.

---

dialect.go
dialect_common.go
dialects/mssql/mssql.go
main.go
search.go

Accept an int64 for limit/offset values to ensure values greater than 2 billion (signed 32-bit max) are addressable via `LIMIT X OFFSET Y`.
Unit-test output for `GORM_DIALECT=postgres`:
jay@gigawatt-io:~/go/src/github.com/jinzhu/gorm$ GORM_DIALECT=postgres go test ./...
ok  	github.com/jinzhu/gorm	3.174s
?   	github.com/jinzhu/gorm/dialects/mssql	[no test files]
?   	github.com/jinzhu/gorm/dialects/mysql	[no test files]
?   	github.com/jinzhu/gorm/dialects/postgres	[no test files]
?   	github.com/jinzhu/gorm/dialects/sqlite	[no test files]
jay@gigawatt-io:~/go/src/github.com/jinzhu/gorm$ echo $?
0
Details and context:
Prior to January 2016 the limit/offset values were `interface{}`.  This regression in functionality (which makes it impossible to paginate an offset beyond approx. ~2 …

Use int64 for limit/offset values to ensure values > 32-bit int are addressable.

---

migration_test.go
scope.go

The indexes work as before but you can now add multiple by comma separating them.
If you leave one of the comma separated values empty it is assumed you want to create the default index.

Add support for multiple indexes seperated by commas for issue #884

---

dialect.go
dialect_common.go
dialects/mssql/mssql.go
main.go
search.go

Revert "Use int64 for limit/offset values to ensure values > 32-bit int are addressable."

---

create_test.go
dialect_mysql.go
migration_test.go
model_struct.go

In the current implementation, AUTO_INCREMENT on simple attributes does not work on postgres.
This PR fixes that.

Fix autoincrement

---

callback_query_preload.go
preload_test.go

This PR fixes a bug with preloads of `has many` related objects would be duplicated many times when using `Find` method. Consider this example:
```
type (
Postcode struct {
ID     uint
AreaID uint
}
Area struct {
ID         uint
Postcodes []*Postcode
}
User struct {
ID       uint
}
UserArea struct {
ID     uint
UserID uint
User   *User
AreaID uint
Area   *Area
}
)
```
In the structure above, we have multiple areas in our database such as `London`, `Paris`. Each area has a list of postcodes assigned to it, e.g. `EC1`, `EC2`.
We can then create a user area objects related to specific users. For example, a db structure like above could be used to store data about users wanting to buy / sell properties in different areas.
Now the bug is, if we create an area for `London` and assign two …

Fixed bug when preload duplicates has many related objects.

---

documents/README.md
documents/database.md

Adds `defer db.Close()` to README.md's "getting started" example as well as the Database Connections section.
This makes it clear that `db.Close()` is important after a `db, err := gorm.Open(...)`.
Looking at [sourcegraph.com](https://sourcegraph.com), there are [219 repositories](https://sourcegraph.com/github.com/jinzhu/gorm/-/info/GoPackage/github.com/jinzhu/gorm/-/Open) referencing `gorm.Open(...)` and only [38 repositories](https://sourcegraph.com/github.com/jinzhu/gorm/-/info/GoPackage/github.com/jinzhu/gorm/-/DB/Close) referencing `gorm.Close()`. That indicates people could benefit from the example.
---
Note: I am purposely omitting a `nil` check for `db` in the example but it can be added to be more verbose and safe when coding. Something like:
```
db, err := gorm.Open(...)
if err …
```

Add db.Close() examples to documentation

---

main.go

if db.Ping() is error,  we should close db and return error. fix for #1189

fix goroutine leak while calling db.Ping() error

---

association.go
callback_query_preload.go
callback_save.go
migration_test.go
model_struct.go
polymorphic_test.go
scope.go

Use case 1:
Hamster has 2 type of toys, preferred and the other.
Use case 2:
School has hall photo and set of individual photos for classrooms.
To save both types of sub-object into one table you need to set relation on something else than table name. 
Solution - add "value" into struct tag:
```
type Hamster struct {
Id           int
Name         string
PreferredToy Toy `gorm:"polymorphic:Owner;value:hamster_preferred"`
OtherToy     Toy `gorm:"polymorphic:Owner;value:hamster_other"`
}
```

Add named value for PolymorphicType (to optionally replace scope.TableName)

---

callback_query_preload.go
preload_test.go

When using `Preload` to include the results of a "has many"
relationship, Gorm previously returned an uninitialized slice for any
such relations that bore zero records. This distinction was most
apparent when the results were marshalled to a JSON representation--a
record with zero related records would be represented with `null`.
For example, consider the following schema:
id | name
---|------
1  | Lorin
2  | Sue
id | p_id | value
---|------|-------------------
1  | 1    | lorin@example.com
2  | 1    | lorin2@example.com
Querying with:
db.Preload("Email").Find(&people)
And marshalling the resulting value of `people` to JSON would yield the
following string:
[
{
"name": "Lorin",
"email": [
"lorin@example.com",
"lorin2@example.com"
]
},
{
"name": "Sue",
"email": null
}
]
Beyond being …

Return empty slice for associations with 0 results

---

main.go
main_test.go

This is the scenario:
1. Caller side calls the Open without argument
2. Caller side calls the Close afterwards when `err != nil` - [this will panic](https://github.com/almighty/almighty-core/pull/344#discussion_r82363818)

If no arguments, return error at once

---

errors.go
errors_test.go
main.go

gorm.Errors, which usefully implements `error` for an `[]error` as returned by
`DB.GetError()` was already exported, but because it used a private field
`errors`, it was not able to be created due to the compile-time error:
```
implicit assignment of unexported field 'errors' in gorm.Errors literal
```
The trivial solution would be to export the `errors` field on
`gorm.Errors`, but this led to the issue that the common pattern of checking
`err != nil` failed because a struct{error: nil} != nil.
We can take advantage of type aliasing here to make Errors an []error, which
can in fact be nil and would pass `err != nil` on the happy path.
- Remove `(Errors) GetErrors()`, as it's less useful when Errors is an
[]error which can be iterated over. While this is technically a
breaking change, we …

Make gorm.Errors available for use outside gorm

---

callback_delete.go
callback_update.go
main.go
main_test.go
scope.go

In some cases (Error not checked, missed data) one can perform very harmful operation - global update or delete (all records)
DB.BlockGlobalUpdate(true) prevents it.

Block global updates / deletes

---

scope.go
utils.go

@jinzhu Please take a look.
This change pulls regexp compilation out of some (potentially) hot functions to be done ahead of time.
This leads to a small performance increase with little cost.
I can wrangle up some benchmarks if you really want proof but it should be fairly self-evident, this work will now only be done one time vs. several times. 
Signed-off-by: Xavier Sandal <sandalwing@sandalwing.com>

Compile regexp ahead of time

---

models.html

there's a typo in a link on the models.html page to curd.html instead of crud.html.

fix link typo

---

documents/associations.md

AssociationForeignKey must be the same type of ForeignKey
ForeignKey is better to be uint as gorm.Model.ID is uint

associations.md: updated association fields type

---

documents/crud.md

Documenting the limitation on the `func (s *DB) First(out interface{}, where ...interface{}) *DB` method where the column name is optional if the primary key is numeric. In other cases, the name of the column must be provided.

Clarification on `DB.First(...)` method

---

dialects/mssql/mssql.go

Fixes #1205
Simple applying @dipbhi's fix from https://github.com/jinzhu/gorm/issues/1205#issuecomment-260104461
Solves my issues with `(mssql: Invalid usage of the option NEXT in the FETCH statement.)`

Fix issue with mssql NEXT option.

---

dialect.go
dialect_common.go
dialects/mssql/mssql.go
interface.go
main.go
scope.go

Exporting sqlCommon as SQLCommon.
This allows passing alternate implementations of the database connection, or wrapping the connection with middleware.  This change didn't change any usages of the database variables.  All usages were already only using the functions defined in SQLCommon.
This does cause a breaking change in Dialect, since *sql.DB was referenced in the interface.

Replace all use of *sql.DB with sqlCommon

---

dialect_sqlite3.go

Removing this line as there's no significant need for it. In fact, it was confusing me as a developer using the API.
Even though SQLite is registered with the `sqlite` dialect through GORM, when it's passed to `mattn/go-sqlite3`, it will throw an error.
Using the following code:
```go
gorm, err := gorm.Open("sqlite", "db.sqlite")
```
will result in the following error:
```go
sql: unknown driver "sqlite" (forgotten import?)
```
Given that you must use `sqlite3` to use SQLite, this line is unnecessary.

Remove 'sqlite' dialect registration

---

query_test.go
search.go

Hi,
First of all, thanks and congratulations for this great project. I apologize in advance if i'm wrong and if I'm putting my hand where I should not.
After update one of my projects to the last development version of GORM, I have found a little bug in the sort function when executing queries. The problem appears when you **pass** an **empty string** to the sort/order function which currently produces an SQL syntax error. 
Example: 
```go
sortBy := ""
if useCustomSort() {
sortBy = buildSortClause()
}
db.Order(sortBy).Find(&users)
Result:
Error 1064: You have an error in your SQL syntax; check the manual...
```
After review the [search.go](https://github.com/jinzhu/gorm/blob/master/search.go) file history changes, I have found that the problem was introduced by "[Add ORDER BY sql …

Fix empty string as order/sort clause

---

callback_query.go

Errors comings from DB have higher priority than logic ones.
Even if it's correct to emit a ErrRecordNotFound it is misleading as the following ( common ) use case:
```go
if db.RecordNotFound() {
/* 404 */
} else if db.Error != nil {
/* 500 */
}
```
Note that the opposite usage is not possible as `ErrRecordNotFound` is part of db.Error, leading to 500 when it should be a 404.
A better solution is to manage ErrRecordNotFound differently from db ones, such that `db.Error` and `db.GetErrors()` does not include it as it is not an error but a normal and expected result.
Thank you in advance for your time and all the great work you did so far :blush:

DB errors over NotFound

---

utils.go
utils_test.go

Thank you very much for letting me use it very conveniently
The behavior of the ToDBName method when the last capital letter comes in like FieldX has been corrected
FieldX becomes fieldx if it wants to become field_x
I am glad if you check it

Fix ToDBName method

---

main.go

fixes 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x645406]
goroutine 8 [running]:
panic(0x924a60, 0xc42000c0f0)
/home/slayer/.gvm/gos/go1.7/src/runtime/panic.go:500 +0x1a1
database/sql.(*Tx).Commit(0x0, 0x7f3836324fa8, 0x0)
/home/slayer/.gvm/gos/go1.7/src/database/sql/sql.go:1249 +0x26
github.com/jinzhu/gorm.(*DB).Commit(0xc43f079710, 0x9b3978)
/home/slayer/.gvm/pkgsets/go1.7/global/src/github.com/jinzhu/gorm/main.go:463 +0x81
```

prevent nil pointer dereference on closed connection

---

dialect_common.go
dialect_mysql.go
dialect_postgres.go
dialect_sqlite3.go
dialects/mssql/mssql.go

1. Sqllite would not support slices, so objects like:
```
type MyByteSlice []byte
```
would crashing on auto-migrate. 
2. MSSQL needs to use varbinary or image to avoid codepage issues and conflicts. 
3. Exported the previously private IsByteArrayOrSlice (originally in dialect_postgres.go), so it can be used generically throughout.

Adding more complete binary support for standard dialects

---

callback_query_preload.go
preload_test.go

- []X New code/logic commented & tested
Thank you.
This PR adds a scope feature setting gorm:auto_preload. This causes all association to preload, including nested objects. This is a convenience method to eliminate many calls to Preload() for larger models and ensure consistency when all association preloads are needed.

gorm:auto_preload setting to enable auto preloading associations

---

documents/advanced.md

I fixed little typo in advanced document

Typo in "advanced" document

---

scope.go

I am using numbers for column names (to be compatible with protobuf) and adding unique index to them does not work since they are not quoted. I do not see a reason to check if the column name is a string in order to quote it. Correct me if I am wrong.

Updated scope.go to always quote when adding index

---

dialect_postgres.go

The integer type in postgres is 4 bytes. Since it is also signed, when using uint32 with high bit set you will get:
`pq: value "2854263694" is out of range for type integer`
To prevent this uint32 should be bigint in postgres.

Changed the type of uint32 from integer to bigint in postgres

---

dialect_postgres.go

If a postgres database contains more than one
schema methods like HasTable(...) would return
true even if the current schema does not contain a
table with that name.
The [INFORMATION_SCHEMA](https://www.postgresql.org/docs/9.6/static/infoschema-tables.html) tables have a column 
named `table_schema` and the [pg_indexes](https://www.postgresql.org/docs/9.6/static/view-pg-indexes.html) table a 
similar one named `schemaname`.
I added a check to the `where` clause of the respective
queries to only look at the [current schema](https://www.postgresql.org/docs/9.6/static/functions-info.html).

Fix postgres dialect for databases with multiple schemas

---

errors.go

Thank you.
To skip nil in `Add` .
I wrote the following code.
```
conn *gorm.DB
...
tx := conn.Begin()
var errs gorm.Errors
errs = errs.Add(tx.Delete(&foo).Error)
errs = errs.Add(tx.Delete(&bar).Error)
if errs.Error() != "" {
tx.Rollback()
return
}
...
```
I got the error.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x43e6f75]
```
I checked `errs` variable.
```
gorm.Errors{
nil,
}
```
I think `Errors` doesn't need to have `nil`.
Or should I always write like this?
```
if err …
```

Erros skip nil in Add function

---

search.go

Thank you.
I am trying to run query like this:
`DB.Model(&Entry{}).Select("DISTINCT date_part('year', created_at) as year").Order("year desc")`
And the years are not ordered. I am not sure what the reasoning behind ignoring order on distinct was, but I need the years ordered.

Do not ignore order on distinct query

---

dialect_postgres.go

This is needed for proper cloud sql proxy.
see https://github.com/GoogleCloudPlatform/cloudsql-proxy and https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/proxy/dialers/postgres/hook_test.go for details.
With this patch the gorm dialect of cloudsqlpostgres is recognised as postgres.
Does not look like a unit testable commit.
Thank you.

Support cloudsqlpostgres dialect

---

migration_test.go
scope.go

The generated SQL for ModifyColumn was:
`ALTER TABLE "tablename" MODIFY "columname" type`
But should have been:
`ALTER TABLE "tablename" ALTER COLUMN "columname" TYPE type`
since Modify does not seem to be entirely compatible with all Engines
- [] No API-breaking changes
- [] Write good commit message, try to squash your commits into a single one
Thank you.

Correct ModifyColumn SQL syntax.

---

dialect_common.go
dialect_mysql.go

Thank you.
Fix #1681
https://github.com/jinzhu/gorm/blob/0a51f6cdc55d1650d9ed3b4c13026cfa9133b01e/dialect_common.go#L147-L151
`(_*[^a-zA-Z]+_*|_+)`
```go
db.Model(&Example{}).AddForeignKey("__example6__id_", "_example1_(_id0__)__", "RESTRICT", "RESTRICT")
// => examples_example_id_example_id_foreign
```
`[^a-zA-Z0-9]+`
```go
db.Model(&Example{}).AddForeignKey("__example6__id_", "_example1_(_id0__)__", "RESTRICT", "RESTRICT")
// => examples_example6_id_example1_id0_foreign
```

Fix regex in BuildForeignKeyName #1681

---

scope.go

`autoIndex` should throw an error when it failed to create an index, such as when you use `AutoMigrate` or `CreateTable`.

autoIndex should throw an error on failed

---

documents/database.md

remove ```sslmode=disable``` from postgresql which leads to unsafe copy and paste situations

remove sslmode=disable from postgresql docu

---

documents/SUMMARY.md
documents/dialects.md

Add section on Dialects to the documentation. For now, it only has info on column specific fields in PostgreSQL, but this can be extended later to include information on the other supported dialects and quirks/pitfalls that might be present when using gorm with specific dialects.

Add section on Dialects to the documentation

---

.github/PULL_REQUEST_TEMPLATE.md

Only a small change.
`a` agreement => `an` agreement
Thank you.
Change the pull request template to use an instead of a when the article AN is used before singular, countable nouns which begin with vowel sounds.

Update PULL_REQUEST_TEMPLATE.md, A vs. An

---

callback_query.go
callback_query_preload.go
preload_test.go

When using `Preload` on a `many2many` association, the `Query` callback chain was not being called. This made it difficult to write a plugin that could reliably get called regardless of how objects were being queried.
Now `handleManyToManyPreload` will call the `Query` callback chain for each object that is retrieved by following the association.
Since the data has already been read by the`handleManyToManyPreload` method, a new scope setting called `gorm:skip_queryCallback` is set to `true` before calling the callbacks. Callbacks can check for the presence of this setting if they should not be run; the default `queryCallback` is an example of this case.
Fixes jinzhu/gorm#1621.

Call Query callback chain when preloading many2many

---

callback_update.go

Thank you.
Addresses #1700. 
I tested it by looking at the `SQL` field of the scope in `DB.UpdateColumns`. Across multiple runs, the generated SQL did not change.

Sort column names before generating SQL in `DB.UpdateColumns`

---

main.go

`NewScope` clones `DB` no need to chain a call to clone with `NewScope`.

Removed unnecessary cloning.

---

main.go

gorm is affected by a whole class of bugs due to the (in)famous [nil interface comparison](https://golang.org/doc/faq#nil_error) problem.
If the developer does not check for `.Error` after calling `.Begin()`, then a panic will be triggered when calling `.Commit()` after a (silently) failed `Begin()`. It would be best that all gorm APIs returned an error as last parameter as normal Go code does, but that is another topic.
Code that will trigger the panic in case of `Begin()` failure:
```
var db *gorm.DB
// ... initialise db ...
tx := db.Begin()
// NOTICE here how no error is checked
// panic will always happen here when `Begin()` failed before
tx.Commit()
```
```
2018/04/03 03:07:22 http: panic serving 10.212.4.0:51123: runtime error: invalid memory address or nil pointer dereference …
```

Do not panic if Begin().Error was ignored

---

scope.go

- [✅] Do only one thing
- [✅] No API-breaking changes
- [✅] New code/logic commented & tested
scope.removeForeignKey doesn't *actually* remove a foreign key because scope.addForeignKey passed a parameter to BuildKeyName that remove didn't. I have since remedied this

fix scope.removeForeignKey method

---

main.go
main_test.go

Simply check if the passed-in database source meets the expected types
and, if not, early return with error.
This caused me to lose nearly an hour trying to debug why I was getting nil pointer errors, only to find out I was passing in a string pointer instead of a string. A simple input validation here would have errored me out early and I could have discovered my dumb mistake much earlier :)

add simple input validation on gorm.Open function

---

dialect.go

This PR adds a GetDialect function that returns existing dialects.
We need the ability to connect to a database through an SSH tunnel while using gorm. This can be accomplished like so: https://gist.github.com/vinzenz/7b6b1bf8d0c2b2b1e0d69a15ba9f02c7 
The problem occurs here:
```go
sql.Register("postgres+ssh", &ViaSSHDialer{sshcon})
db, err = gorm.Open("postgres+ssh", options.ContentDBDSN)
```
The database connects just fine buts runs under compatibility mode and you get the following warning message:
```
`postgres+ssh` is not officially supported, running under compatibility mode.
```
Running under compatibility mode breaks any …

Adding GetDialect method to fetch existing gorm.Dialect implementations

---

main.go

Fixes issue #1830 when db `Rollback()`
```
2018/05/04 11:35:02 http: panic serving 127.0.0.1:51133: runtime error: invalid memory address or nil pointer dereference
goroutine 257 [running]:
net/http.(*conn).serve.func1(0xc42027a640)
.../dev/go/src/net/http/server.go:1726 +0xd0
panic(0x14600e0, 0x17842e0)
.../dev/go/src/runtime/panic.go:505 +0x229
database/sql.(*Tx).rollback(0x0, 0x14c5500, 0x1, 0x1a96480)
.../dev/go/src/database/sql/sql.go:1944 +0x2d
database/sql.(*Tx).Rollback(0x0, 0x1a91408, 0x0) …
```

Do not panic if Begin().Error was ignored (#1830)

---

dialects/mssql/mssql.go

SQL Server 2016 has significant support for JSON values. While it has no special json data type, storing JSON values in NVARCHAR columns is getting common now. With this addition to the mssql dialect it's easy to fetch JSON values from SQL Server, similar to the postgres.Jsonb type.

Adding json type for mssql dialect, similar to postgres.Jsonb

---

scope.go

- [+] Do only one thing
- [+] No API-breaking changes
- [+] New code/logic commented & tested
Previously removeForeignKey method didn't generate a proper query for MySQL dialect.

Fixed mysql query syntax for FK removal

---

callback_query_preload.go
preload_test.go

Currently if you set `gorm:auto_preload` to `false`, it still preloads data.  This PR makes it so that doesn't happen.

Setting gorm:auto_preload to false now prevents preloading

---

scope.go

- [+] Do only one thing
- [+] No API-breaking changes
- [+] New code/logic commented & tested
Change buildCondition TableName to struct's TableName when query is interface{}. It's very useful when  joining table

Change buildCondition TableName to struct's TableName when query is interface{}

---

main_test.go
scope.go

Fix a bug in `Scope.scan` where fields with repeated names are not incorrectly skipped. Specifically, values in `selectedColumns` must be indexed relative to `fields`, not `selectFields`.
Add a test demonstrating how a SELECT query with three ID fields from a joined table can be used to populate a single struct with the correct values. (The test fails without this fix.)

Fix scanning identical column names occurring >2 times

---

main.go

When using Gorm in a production environment, we experienced fatal errors caused by concurrent map reads/writes. We traced this down to `DB.values`, and when we put a mutex around this map, the concurrent reads/writes stopped. However, we noticed that other parts of Gorm seem to prefer `sync.Map`, so this pull request replaces `DB.values` with a `sync.Map`.
(Relevant issue: https://github.com/jinzhu/gorm/issues/2065)

Use sync.Map for DB.values

---

utils.go

The `IsValid` sanity check in the `getValueFromFields` would return `true` even if `fieldValue` was nil. Wrapping `fieldValue` in a `reflect.Indirect` fixes the issue.

Fixes nested-preload for rows with nil pointers

---

callback_update.go

We found an issue where Gorm was trying to write the zero value of a has_one foreign key into the table and when using actual database foreign keys, the value `0` was invalid. This pull request adds a check in the `updateCallback` to ensure the field being update is not a blank foreign key with a default value. In our case the has_one relationship has a default value of null in the event that the model does not have the child yet. 
All gorm tests pass and this makes it safe to use foreign keys with a default value of null.

Fix issue updating models with foreign key constraints

---

callback_query.go
main.go

Add function to only preload an already populated/initialized model. Very small and simple change. Using to preload simple fields of an model with custom sql on a performance-critical context.

Support only preloading 

---

association.go

From effective Go: https://golang.org/doc/effective_go.html#switch
> It's therefore possible—and idiomatic—to write an if-else-if-else chain as a switch.

rewrite if-else chain as switch statement

---

field.go
field_test.go

convert via valuer interface before do scan.
Scan interface only accept int64, float64, bool, []byte, string,
time.Time or nil. When do scan, it's better to check whether the type
support valuer interface and do convert.

Check valuer interface before scan value

---

logger.go

---
such as:
---
#idres field is int
SELECT count(*) FROM xxxx  WHERE idres = **`'22' `**
SELECT count(*) FROM xxxx  WHERE idres = **`22`**
---
remove quote `''` when  **int, int16, int32, int64, int8, float32, float64**.
-----

Better log output int8, int, int16, int32, int64, float32, float64, bool.

---

field_test.go
go.mod
go.sum

gofrs/uuid was used in testing only, and go module count testing
depends in. This patch removed the gofrs/uuid depends, and appengine
as well.

Removed the deps on uuid and appengine

---

model_struct.go

when `str` variable is `empty string`, TagSettings' map  has  `"":""`  value like this:
and this code will `print 1` although the `str` variable is empty string:
```go
str := ""
tags := strings.Split(str, ";")
fmt.Println(len(tags))
```
try this: https://play.golang.org/p/ISj1UhSlB4x

fix TagSettings' map  has "":"" value

---

main_test.go
scope.go

```go
type OwnerEntity struct {
gorm.Model
OwnerID   uint
OwnerType string
}
type SomeEntity struct {
gorm.Model
Name        string
OwnerEntity OwnerEntity `gorm:"polymorphic:Owner"`
}
db := DB.Debug()
db.DropTable(&SomeEntity{})
db.AutoMigrate(&SomeEntity{})
a := SomeEntity{Name: "test"}
db.Model(&a).Where(a).Updates(SomeEntity{Name: "test2"})
// will panic: runtime error: invalid memory address or nil pointer dereference
```
because tag `gorm:"polymorphic"` will execute the following code but scope.db is nil:
```go
relationship.PolymorphicValue = scope.TableName() …
```

Fixed nil error when first updates with struct

---

callback.go
callback_system_test.go
main.go

Pass the db's logger into Callback{} so that the same logger is used for callback registration and removal.
[Fixes #1825]

Pass logger into Callback{} so that logs are printed consistently

---

main.go
main_test.go

When db.Rollback fails, check the error code. If it matches sql.ErrTxDone, we won't treat it as an error. This is expected and normal behavior of using Rollback with defer.
e.g: 
```go
tx := db.Begin()
defer tx.Rollback()
...
return tx.Commit().Error
```
See more discussion here: https://github.com/go-gormigrate/gormigrate/issues/36

Don't AddError for Rollback on ErrTxDone

---

query_test.go
scope.go

Fix #2517 : Check for incomplete parentheses to prevent SQL injection.

---

logger.go

```
logger:
[sql D:/mygo/src/ch/t/run.go:309 1.9954ms INSERT  INTO `a` (`user_id`,`vip_expire_time`,`message_type`,`click_tab_time`) VALUES (?,?,?,?) [0 0001-01-01 00:00:00 +0000 UTC  0001-01-01 00:00:00 +0000 UTC] 1]
?[33m[2019-08-28 10:53:01]?[0m  ?[36;1m[0.99ms]?[0m  INSERT  INTO `a` (`user_id`,`vip_expire_time`,`message_type`,`click_tab_time`) VALUES (3,'0001-01-01 00:00:00','hello','0001-01-01 00:00:00')
```
check timezero:
```
INSERT  INTO `a` (`user_id`,`vip_expire_time`,`message_type`,`click_tab_time`) VALUES (3,'0000-00-00 00:00:00','hello','0000-00-00 …
```

fix gorm logger insert timezero 0001-01-01

---

query_test.go
scope.go

This reverts commit e3cc5ea4d403078a370e299629da56cd011b6583 from https://github.com/jinzhu/gorm/pull/2519 due to breaking of valid queries.

Revert check for incomplete parentheses

---

main.go
scope.go
search.go
utils.go

In several cases I've really wanted the ability to return the result of calling `QueryExpr` from a function.  The `expr` type being private prevents being able to write a function that returns or accepts it.  The public constructor for this type doesn't do anything besides forward the args.  I'm assuming this was private in the first place to allow future refactoring, but this has been stable for some time.  This would be a significant usability improvement.

Rename expr type to make it public.

---

dialect_mysql.go

allow mysql database name with '-' character
implement issue #2715 
allow mysql database name with '-' character
dialect_mysql.go line:168
```go
func (s mysql) HasTable(tableName string) bool {
currentDatabase, tableName := currentDatabaseAndTable(&s, tableName)
var name string
// allow mysql database name with '-' character
if err := s.db.QueryRow(fmt.Sprintf("SHOW TABLES FROM `%s` WHERE `Tables_in_%s` = ?", currentDatabase, currentDatabase), tableName).Scan(&name); err != nil {
if err == sql.ErrNoRows {
return false
}
panic(err)
} else {
return true
}
}
```

fix(HasTable): database name

---

callback.go

Prior to this PR callback `Remove` and `Replace` both log the action being taken. This change brings similar functionality to `Register`.

Log callback registration if logger exists for consistency

---

model_struct.go
model_struct_test.go

When you run tests with the `-race` flag there's a small chance to hit a race condition in gorm.  
This particular race condition is harmless, but it's very annoying when a CI pipeline fails over it and if everyone who get's it at some point has to debug to figure out what is going on that's a lot of needless time wasted ...
The `foreignField.IsForeignKey = true` line can be hit in a few different scenarios (there's also 3 places where it's done), either when 2 models have the same relation or when the same model is used for the "first time" in parallel.
I've added a global mutex to use, I think it might be more "correct" to add a mutex to `StructField`, but it seems like overkill to create so many mutex.  
If you guys …

fix a race condition on IsForeignKey that is being detected by -race

---

main.go
main_test.go

Before:
```go
func CreateAnimals(db *gorm.DB) error {
tx := db.Begin()
defer func() {
if r := recover(); r != nil {
tx.Rollback()
}
}()
if err := tx.Error; err != nil {
return err
}
if err := tx.Create(&Animal{Name: "Giraffe"}).Error; err != nil {
tx.Rollback()
return err
}
if err := tx.Create(&Animal{Name: "Lion"}).Error; err != nil {
tx.Rollback()
return err
}
return tx.Commit().Error
}
```
After:
```go
func CreateAnimals(db *gorm.DB) error {
return db.Transaction(func(tx *gorm.DB) error {
if err := tx.Create(&Animal{Name: "Giraffe"}).Error; err != nil {
// return any error will rollback
return err
}
if err := tx.Create(&Animal{Name: "Lion"}).Error; err != nil {
return err
}
// return nil will commit
return nil
})
}
```

Add `db.Transaction` method for create Transaction block.

---

main.go
main_test.go

This improves upon #2767.
Previously, the code would swallow any panics, which isn't ideal;
panic is intended to be used when a critical error arises,
where the process should fail fast instead of trying to limp along.
This now defers the any recovery (if desired) to the client code.

transaction blocks: don't swallow panics

---

go.mod
go.sum

The reason to update this package was goroutine leak in v1.4.1, which occurred when used idle MySQL connections.

updated go-sql-driver package

---

main_test.go

Panic will rollback case should use "transaction-3".
Fix TestTransactionWithBlock panic case

Fix TestTransactionWithBlock panic case

---

clause/group_by.go
clause/order_by.go
clause/set.go
clause/where.go
statement_test.go

This is an updated fix for jinzhu/gorm #3007 for the new code base.  While the
overall structure has changed drastically, the primary issue behind
the original problem is still present.  In this case, `MergeClause` does
not create a proper copy and instead allows for two clauses to have
the same backing array.
----
Method-chaining in gorm is predicated on a `Clause`'s `MergeClause`
method ensuring that the two clauses are disconnected in terms of
pointers (at least in the Where case).
However, the original Where implementation used `append`, which
only returns a new instance if the backing array needs to be resized.
In some cases, this is true.  Practically, go doubles the size of the
slice once it gets full, so the following slice `append` calls would
result in a new slice:
* 0 -> 1
* 1 …

Fix Statement Where clone array corruption in v2

---

chainable_api.go
finisher_api.go
statement.go
statement_test.go

This fixes a spelling error in the word "condition"; in particular,
the `BuildCondtion` function should be named `BuildCondition`.

Spelling fix for "condtion" -> "condition"

---

tests/create_test.go

This PR fixes typos in test method names in `create_test.go`. `PrimayKey` -> `PrimaryKey` and `Strut` -> `Struct`.

Fix spelling errors in test method names

---

schema/schema.go
tests/create_test.go

Create function supports batch create, but only Slice is supported.
There are cases where it would be desirable if Array could be used in some cases.
For example, when using faker to create a fixed number of records.
This change supports it.
-----
By the way, in my local PC the other test failed than before the PR, but I ignored it.
It seems that the return value of test script is always 0 (it means success)
Please use the patch below.
```diff
diff --git a/tests/tests_all.sh b/tests/tests_all.sh
index a321fe3..f85a7a4 100755
--- a/tests/tests_all.sh
+++ …
```

Create supports Array / ArrayPtr

---

clause/limit.go
clause/limit_test.go
tests/query_test.go

修复当 `limit` 为非正整数时，`offset` 的设置将无效的问题。
1. 仅设置 `offset`，能正常追加到 `SQL`
1. 多次设置  `offset`，将使用最后设置的值
1. 设置 `offset` 后可再次设置 `limit`，互不干涉

fix no limit no offset.

---

callbacks/update.go
schema/field.go
tests/customize_field_test.go

- [] Tested
`
CreatedAt time.Time // Set to current time if it is zero on creating
UpdatedAt int       // Set to current unix seconds on updaing or if it is zero on creating
Updated   int64 `gorm:"autoUpdateTime:milli"` // Use unix MILLI seconds as updating time
Created   int64 `gorm:"autoCreateTime"`      // Use unix seconds as creating time
}
`

Auto creating/updating time with unix (milli) second

---

chainable_api.go
finisher_api.go

Hi,
This PR is a minor change.
- delete unused default in case statement. 
- like any other function, Changed to not set variable in return statement.
`return tx`→`return`

fix return value and delete unused default

---

logger/sql.go
schema/field.go
utils/utils.go

strconv.Format comparison fmt.Sprint () has better performance and occupancy

fmt.Sprint() to strconv.Format

---

logger/logger.go

This pull request fixed the logger output execution time format in mono color mode was different from colorful mode.
In mono color mode, the execution time output: [0]
In colorful mode, the execution time output: [0.001ms]

Fix monocolor log output inconsist with colorful log

---

migrator/migrator.go

When the migrator is used to discover the column types, such as when
used with `AutoMigrate()`, it does not close the query result. This
changes the migrator to close the query result and it also changes the
query to use `LIMIT 1` to prevent additional work against the database
when only discovering the schema.
Fixes #3432.

Release the connection when discovering the column types in the migrator

---

logger/sql.go
logger/sql_test.go

Fix format sql log

---

logger/sql.go

if the field is null, then  not "<nil>",  but "NULL" is written.
if type is fmt.Stringer() and fmt.Sprintf("%v", v) is used , it does not trigger the Stringer() function of the object.That is why it gives '' not NULL as we wanted. The case fmt.Stringer is removed from the switch and pushed.
```
type UserWithUUID struct {
ID        uint `gorm:"primarykey"`
CreatedAt time.Time
UpdatedAt time.Time
TestID     *uuid.UUID `gorm:"type:uuid"`
}
value := UserWithUUID{}
createErr := DB.Save(&value).Error
```
Before :
INSERT INTO "user_with_uuids" ("created_at","updated_at","test_id") VALUES ('2020-10-14 02:20:47.3','2020-10-14 02:20:47.3','<nil>') 
Now
INSERT INTO `user_with_uuids` (`created_at`,`updated_at`,`test_id`) VALUES ("2020-10-18 00:20:22.765","2020-10-18 00:20:22.765",NULL)

nil point transfer '<nil>' not transfer NULL #3604

---

migrator.go
migrator/migrator.go

Updates the signature of `ColumnTypes` and `MigrateColumn` to rely on an interface (compatible with `sql.ColumnType`). This allows driver to override the `ColumnTypes` function and solve #3628.
Once this PR is merged, I will open two PRs on the `mysql` and `postgres` driver repo to implement a correct `ColumnTypes` method.
`sql.ColumnType` does not always have all information required to automigrate correctly:
- `postgres` does not give nullability information
- `mysql` does not give size information for `char` and `varchar`
For `postgres` and `mysql` the missing information can be retrieved from the `information_schema` table.

add gorm ColumnType interface, remove sql one

---

logger/logger.go

bug所在文件：logger/logger.go， 167 行代码块
相关函数：New 没有初始化 BeginAt参数, 默认值 0001-00-00 00:00:00
```code
type traceRecorder struct {
Interface
BeginAt      time.Time
SQL          string
RowsAffected int64
Err          error
}
func (l traceRecorder) New() *traceRecorder {
return &traceRecorder{Interface: l.Interface}
}
func (l *traceRecorder) Trace(ctx context.Context, begin time.Time, fc func() (string, int64), err error) {
l.BeginAt = begin
l.SQL, l.RowsAffected = fc()
l.Err = err
}
```
触发bug的条件：
相关文件：finisher_api.go ，358行代码段，
调用了函数： logger.Recorder.New()、	newLogger.BeginAt
```code
// Scan scan value to a struct
func (db *DB) Scan(dest interface{}) (tx *DB) {
currentLogger, newLogger := db.Logger, logger.Recorder.New()
tx = db.getInstance()
tx.Logger = newLogger
if rows, err := tx.Rows(); err != nil …
```

修复日志追踪traceRecorder初始化函数New没有赋予默认值导致的bug

---

schema/naming.go

```
BenchmarkToName-8     	  2322307	       521 ns/op	      88 B/op	       5 allocs/op
↓
BenchmarkToName-8     	19997366	        55.0 ns/op	       0 B/op	       0 allocs/op
```
转换后的名字似乎忘记缓存了，缓存后，性能大幅提升

cache converted name

---

association.go
tests/associations_test.go

`Assocoation.Replace()` does not correctly returns error in some switch branches: `schema.HasOne, schema.HasMany and schema.Many2Many`
Create such database structure:
```
type Profile struct {
ID       uint
Number   string
MemberID uint `gorm:"not null"`
}
type Member struct {
ID       uint
Profiles []Profile
}
```
Insert some data:
```
member := &Member{
Profiles: []Profile{{
Number: "1",
}, {
Number: "2",
}},
}
DB.Create(&member)
```
And try to `DB.Model(member).Association("Profiles").Clear()`. No error will be returned but the error actually occurs if you enable the logger

Fix Association.Replace() error returning

---

callbacks/query.go
gorm.go
tests/multi_primary_keys_test.go
tests/query_test.go
tests/table_test.go

Select all the fields of the structures to do the SQL query avoiding SELECT * FROM. It's always better to use the explicit column list in the SELECT query than a * wildcard, #3530
Queries for the `First`, `Take`, `Last`, `Find` methods:
```go
var users []*models.User
db.Debug().Model(&models.User{}).Find(&users)
// SELECT "id","first_name","last_name","email","password","created_at","updated_at" FROM "users"
db.Debug().Find(&users)
// SELECT "id","first_name","last_name","email","password","created_at","updated_at" FROM "users"
```
https://gorm.io/docs/advanced_query.html#Smart-Select-Fields
```go
type APIUser struct {
FirstName string
LastName  string
Email     string
}
db.Debug().Model(&models.User{}).Find(&APIUser{})
// SELECT "first_name","last_name","email" FROM "users"
```
The …

Select all fields in SQL queries avoiding the SELECT * FROM

---

scan.go

int, int64 pointer was scanned correctly, but type int32 pointer was not scanned.
case int
```go
var i int
db.Raw("SELECT 1").Scan(&i)
fmt.Println(i) // <= Print 1
```
case int32
it looks like something is wrong 🤔 
```go
var i int32
db.Raw("SELECT 1").Scan(&i)
fmt.Println(i) // <= Print 0
```
i think, int32 and uint32 pointer would need to be scanned correctly.

Fix Scan int32, uint32

---

scan.go

More base type not support, such as `int8`. NOT support `sql.NullXXX` is fatal.
```sql
SELECT MAX(update_at) FROM tab; # if no any data in tab, will return null.
```
```go
var nullMaxUpdated sql.NullInt64
if err = qp.Raw("SELECT MAX(update_at) FROM tab").Scan(&nullMaxUpdated).Error; err != nil {
return
}
maxUpdated = int(nullMaxUpdated.Int64) // maxUpdated always 0.
```

fix: scan more base type and sql.NullXXX

---

callbacks/associations.go

Fixed #3817.
I’m not sure why did you use `PrioritizedPrimaryField` here, but it causes issues with composite keys, so I removed it.

Fixed creation of associated records with composite primary keys (#3817)

---

clause/expression.go
clause/expression_test.go

This PR fixes [`clause.Eq`](https://github.com/go-gorm/gorm/blob/e1952924e2a844eca52e5030f7b46b78de6ec135/clause/expression.go#L198) and [`clause.Neq`](https://github.com/go-gorm/gorm/blob/e1952924e2a844eca52e5030f7b46b78de6ec135/clause/expression.go#L219) expressions ability to identify `(*T)(nil)` as `nil` values.
The culprit lies in [./clause/expression.go#L206 `clause.Eq`](https://github.com/go-gorm/gorm/blob/e1952924e2a844eca52e5030f7b46b78de6ec135/clause/expression.go#L206) expression that fails to identify `(*T)(nil)` values as `nil` values.
The same problem is present for the [./clause/expression.go#L224 `clause.Neq`](https://github.com/go-gorm/gorm/blob/e1952924e2a844eca52e5030f7b46b78de6ec135/clause/expression.go#L224) expression.
The problem is discussed on [Stackoverflow: …

Fix building of `clause.Eq` and `clause.Neq` expressions that fail to handle `(*T)(nil)` use cases correctly

---

schema/relationship.go

Ensures that schema.Name is Title case before building references in buildMany2ManyRelation. 
We were trying to make a many2many relation gorm tags for a field in our db model, and kept failing due to `"field" is unexported but missing PkgPath`. It seems the schema.Name for our fields were not title case, which blocked us from proceeding to build any further.
In the screenshot, the first 2 schema names already had .Title applied (from the first line of the fix), but as you can see, the 3rd is still lowercase, which lead to the error shown, once we got further along in the codepath.

[Relationship] Title Case schema name for many2many

---

logger/sql.go

In Go’s authentic code specification, when a string or number is called multiple times in multiple places, it is recommended to use magic strings or magic numbers or constants to define it to avoid repetitive work each time.

recommended to use magic const strings

---

schema/check.go

ParseCheckConstraints func
match English letters and midline
Here, the regularity of matching English characters and midline does not have to be a regular compilation operation every time. At the bottom of go reg, the logic here is also consumed. For details, see the implementation of compile and compile of the bottom source code of go reg.

optimization check for ParseCheckConstraints

---

.gitignore
migrator/migrator.go
schema/field.go
tests/migrate_test.go

```
import (
"github.com/shopspring/decimal"
...
)
type ChainExtrinsic struct {
Fee                decimal.Decimal `json:"fee" sql:"type:decimal(30,0);"`//v1
...
}
type ChainExtrinsic struct {
Fee                decimal.Decimal `json:"fee" gorm:"type:decimal(30,0);"`//v2
...
}
db.AutoMigrate()
/*Actually there is no field definition change between v1 and v2.
for mysql migration from gorm v1 to v2 the unnessary alter column ddl as following will be generated
the worst thing is after migrating to v2, will still generate ddl each time when run automigrate
---ALTER TABLE `chain_extrinsics` MODIFY COLUMN `fee` decimal(30,0)
*/
```
we can avoid by add field tag as following:
```
type ChainExtrinsic struct {
Fee                decimal.Decimal `json:"fee" …
```

Add field tag to ignore migration

---

callbacks/associations.go
callbacks/delete.go
callbacks/preload.go
schema/naming.go

Hi, I'm sorry for the trouble I caused you earlier. I'll be careful next time.
This is a small change, but it will send a PR.
There are places where the slice capacity is not specified.
I thought this would be better for Go's slice specification, since the capacity of the slice to be appended can be allocated in advance by the length.

change the method of initializing slice

---

gorm.go

It is used to store the key stored in Config.cacheStore. It is recommended to use a constant. If you need to change, you can use var to modify.

for Config.cacheStore store PreparedStmtDB key

---

chainable_api.go
clause/clause.go
tests/query_test.go

Adds support for named argument In Select API
refer: issue https://github.com/go-gorm/gorm/issues/4140

support named params in Select API 

---

finisher_api.go

To judge the reflection length of the optimized value, the switch operation is performed every time in reflect/value.go in the reflection source code of go. Doing such an operation in for here is actually very performance-consuming. It is recommended to perform it once outside. It's okay.

optimize value of reflection length

---

association.go
callbacks.go
chainable_api.go
clause/clause.go
errors.go
gorm.go
schema/check.go
schema/relationship.go
tests/query_test.go

gorm/schema/relationship.go ParseConstraint method optimization.
The following code is basically called in for. In order to avoid the performance problems caused by repeated compilation of regular expressions, it only needs to be done once outside, so optimization is done here.

Optimize parse constraint

---

callbacks/query.go

-  Do only one thing
Combine "clause.Associations" with "Whatever" in preload, even itself.
This can help to preload all model's children in multiple levels associations.
```
type Person struct {
ID             int      `gorm:"primaryKey"`
FamilySourceID *int
FriendSourceID *int
Family         []Person `gorm:"foreignKey:FamilySourceID"`
Friend         []Person `gorm:"foreignKey:FriendSourceID"`
}
```
if we want to preload all of Person model's children in 4 levels associations, we have to write it as:
```
db.Preload("Family.Family.Family." + clause.Associations).
Preload("Family.Family.Friend."  + clause.Associations).
Preload("Family.Friend.Family."  + clause.Associations).
Preload("Friend.Family.Family."  + clause.Associations).
...
...
Preload("Family.Friend.Friend."  + …
```

support to preload all children in multiple levels associations

---

finisher_api.go
tests/query_test.go

I fixed a bug where there is no way to handle errors inside `FindInBatches` becauses `FindInBatches` ignores errors returned from `Find`.
This is just a bug fix.

Fix FindInBatches to return errors when Find fails

---

schema/naming.go
schema/naming_test.go

Fixed naming longer than 64 characters

---

clause/on_conflict.go

Added some missing spaces.
When using `clause.OnConflict`  with `DoUpdates` a white space was missing.

Added missing white space

---

schema/relationship.go
schema/relationship_test.go
utils/utils.go

This PR is for the issue  #4316 (belongs_to and has_one reversed if field names are identical). 
It fixes the issue which was introduced in [`628a0ae`](https://github.com/go-gorm/gorm/commit/628a0ae707f230c67bca2e632fb302037c707705) commit.
- Added the correct conditions necessary to `reguessOrErr`.
- Added New Test case which handles the use-case that was failing.
- Added a utility function needed.

fixed belongs_to & has_one reversed if field same

---

errors.go

Fixed the error message for `ErrInvalidTransaction` to `invalid transaction` instead of `no valid transaction` because `no valid transaction` is a bit hard to understand and can be misleading sometimes.
For example, we could manually begin a transaction using `tx.Begin` and run `tx.Begin` again but the error message `no valid transaction` can be confusing because there is a transaction already in progress. 
N/A

Fix ErrInvalidTransaction error message

---

schema/relationship.go
schema/relationship_test.go
utils/utils.go

This PR is for the issue #4386 (has_many stopped working if field names are identical).
It fixes the issue which was introduced in [`a222c75`](https://github.com/go-gorm/gorm/pull/4343/commits/a222c758bb1444d192d92c17be13721a8ede0725) commit.
- Corrected the condition.
- Added New Test case which handles the use-case that was failing.

fixed has_many stopped working if field names are identical

---

clause/on_conflict.go

Add target where predicate (index_predicate) to support partial indexes for Upsert in Postgres:
https://postgrespro.com/docs/postgresql/13/sql-insert
( { index_column_name | ( index_expression ) } [ COLLATE collation ] [ opclass ] [, ...] ) [ WHERE index_predicate ]
ON CONSTRAINT constraint_name
In the case when you want to:
- use soft deletion (https://gorm.io/docs/delete.html#Soft-Delete) 
- unique constrain on two or more columns for non deleted rows, like this:
`CREATE UNIQUE INDEX test_index ON table (column1, column2, deleted_at)`
- working on_conflict feature  in gorm (https://gorm.io/docs/create.html#Upsert-On-Conflict)
- Postgres 9.6+
You will figure out, what your index will not work properly because of ignoring null values in deleted_at column: …

Support partial indexes for Upsert in Postgres

---

finisher_api.go

Fixed a bug in finisher_api within the `FirstOrCreate` method. When `FirstOrCreate` was used in conjunction with `Assign` a slice out of bounds error was triggered due to the incorrect usage of the `tx` object.
Using `FirstOrCreate` with `Assign` to handle updates triggered a slice out of bounds error.

Fix: FirstOrCreate slice out of bounds error when using 'Assign'

---

finisher_api.go

- [v] Do only one thing
- [v] Non breaking API changes
- [v] Tested
Use count(*) instead of count(1) include NULL and non-NULL rows, confirm to [SQL-92](https://en.wikipedia.org/wiki/SQL-92).
不使用 `COUNT(col)` 或 `COUNT(常量)` 来替代 `COUNT(*)`, `COUNT(*)` 是 SQL92 定义的标准统计行数的方法，跟数据无关，跟 NULL 和非 NULL 也无关。
see also
- https://dba.stackexchange.com/questions/2511/what-is-the-difference-between-select-count-and-select-countany-non-null-col/2512
- https://stackoverflow.com/questions/1221559/count-vs-count1-sql-server

Use count(*) instead of count(1) include NULL and non-NULL rows(SQL-92).

---

logger/logger.go

I found it hard to understand what the `fc` argument was for in the `logger.Interface` type, so I added return value names.
If this gets merged, I'll open up yet another PR to the `go-gorm/gorm.io` repo

Added return names to logger.Interface.Trace

---

prepare_stmt.go

Fixed a bug in prepare method. In the concurrency case, the mutex gets unlocked before reading the value from **Stmts** and the crash "fatal error: concurrent map read and map write" could appear randomly.
When using PreparedStmtDB.prepare() with a query not cached before for several times at the same time.

fix: fix race issue in prepare method

---

schema/relationship.go

Title join reference schema.Name when building many2many relation.
Fix `panic: reflect.StructOf: field "tagID" is unexported but missing PkgPath` when foreign schema is unexported.
```
type product struct {
gorm.Model
Tags []*tag `gorm:"many2many:product_tags"`
}
type tag struct {
gorm.Model
}
func main() {
// panic: reflect.StructOf: field "tagID" is unexported but missing PkgPath
db.AutoMigrate(&tag{}, &product{})
}
```

title foreign schema for many2many to avoid panic

---

callbacks/query.go
migrator/migrator.go

adjust Preload fmt.Errorf for db.AddError(fmt.Errorf("%v: %w for schema %v", name, gorm.ErrUnsupportedRelation, db.Statement.Schema.Name))
chage it to:
db.AddError(fmt.Errorf("%s: %w for schema %s", name, gorm.ErrUnsupportedRelation, db.Statement.Schema.Name))

adjust Preload fmt.Errorf

---

migrator/migrator.go

fix return value for *schema.Check
checkConstraints := stmt.Schema.ParseCheckConstraints() The return value is a map[string]Check. If the for _,cc mode is applied to the map, it is not the address of the map element.
eg: 
``` go
type Check struct {
name string
}
m := make(map[string]Check, 10)
log.Println("===========for _,cc mode for m=========")
m["a"] = Check{"a"}
m["b"] = Check{"b"}
m["c"] = Check{"c"}
m["d"] = Check{"d"}
for _, cc := range m {
log.Printf("%p", &cc)
}
```
output:
2021/06/17 21:28:34 ===========for _,cc mode for m=========
2021/06/17 21:28:34 0xc00019a370
2021/06/17 21:28:34 0xc00019a370
2021/06/17 21:28:34 0xc00019a370
2021/06/17 21:28:34 0xc00019a370
but use the following way:
``` go
for k := range m {
v := m[k]
log.Printf("%p", &v)
}
```
output:
2021/06/17 21:28:34 …

fix return value for *schema.Check

---

chainable_api.go
tests/query_test.go

This restores the behavior from gorm v1, where calling `DB.Order` with an empty string, nil, or any unexpected type is a no-op.
I work with a REST API framework that parses a custom query syntax for making complicated queries via REST. In gorm v1, we could simply call `db.Order(parsedQuery.Order)`. With gorm.io/gorm, we *must* check `parsedQuery.Order` for empty strings or else gorm.io/gorm generates invalid SQL.
Closes #4429

Do not emit ORDER BY for empty values

---

migrator/migrator.go

The field tag contains `-:migration` and will still be created in AutoMigrate. I think this is a bug.
```go
type testModel struct {
gorm.Model
Name string
Info string `gorm:"-:migration"`
}
if err := db.AutoMigrate(
&testModel{},
); err != nil {
panic(err)
}
```
gorm log before fix:
```sql
CREATE TABLE `test_models`
(
`id`         bigint unsigned AUTO_INCREMENT,
`created_at` datetime(3) NULL,
`updated_at` datetime(3) NULL,
`deleted_at` datetime(3) NULL,
`name`       longtext,
`info`       longtext,
PRIMARY KEY (`id`),
INDEX idx_test_models_deleted_at (`deleted_at`)
)
```
gorm log after fix:
```sql
CREATE TABLE `test_models`
(
`id`         bigint unsigned AUTO_INCREMENT,
`created_at` datetime(3) NULL,
`updated_at` datetime(3) NULL,
`deleted_at` datetime(3) NULL,
`name`       longtext, …
```

Fix create with ignore migration

---

clause/expression_test.go
statement.go
statement_test.go

`Statement.QuoteTo` accept `clause.Expr` as parameter
```go
s.WriteQuoted(clause.Expr{SQL: "SUM(?)", Vars: []interface{}{clause.Column{Table: "users", Name: "id"}}})
```

feat: QuoteTo accept clause.Expr

---

clause/expression.go
tests/query_test.go

Three reasons for this PR:   
1. When `DB.Not(map[string]interface{}{"name": []string{}}).Where("age = ?", 10)`, Generate sql `SELECT * FROM ``users`` WHERE   AND ``age`` = 10;` , it is a bad sql.
2. In some database, like postgresql, when exec ` ``name`` NOT IN ('jinzhu')`, the result dose not contain the row where `name` == NULL, so when `is not` in an empty array,  to some extent, it can be considered that `name` IS NOT NULL. 
3. NegationBuild() should be the inverse of Build(), but when len(values)==0, the Build() return the row where `name`==NULL, so NegationBuild() should not return the row where `name`==NULL. 
```go
DB.Not(map[string]interface{}{"name": []string{}}).Where("age = ?", 10).Find(&User{})`   
```
Thanks!

Fix extra 'AND' when len(values) == 0 ON IN.NegationBuild()

---

callbacks/update.go
tests/update_test.go

Refactor update record

---

clause/expression.go
clause/expression_test.go

Example: select * from table_name where name == @name;
Allow the sql stmt terminator ";" at the end of a named parameter.
Example: 
`select * from table_name where name == @name;`
Allow the stmt terminator `;` at the end of the stmt without a space between it and the named parameter.

fix (clause/expression): Allow sql stmt terminator

---

finisher_api.go
tests/distinct_test.go

- [] Tested
it causes problem when use **Scope** to set TableName and  use **Pluck**.
a demo is provided below.
```
func Find() error {
db := GetDBConnection()
var ids []int
db.Scopes(func(db *gorm.DB) *gorm.DB {
return db.Table("users")
}).Debug().Pluck("id", &ids)
return nil
}
// result: model value required
```

fix:remove the tableName judgment in pluck

---

gorm.go
tests/sql_builder_test.go

@jinzhu 上次讨论的在 Statement 上实现 `ToSQL` 的方法，经过我分析发现按目前 Gorm 已有的实现是无法做到的。
因为有很多的 SQL 实际是在 callbacks 文件夹下的各种最终的函数处实现的，所以看起来得在目前我实现这部分 finisher_api 里面增加动作。
目前的逻辑大概是先声明进入 SQL Builder 模式（在 Statement 开启 DryRun 的 Session），然后 Find, First, Create, Update, Save 这类 Finisher API 执行到 callbacks 里面的 Execute 的时候，不做实际查询。最后调用 `ToSQL` 生成 SQL 字符串，再重置状态。
使用效果：
```go
sql = DB.BuildSQL()
.Model(&User{})
.Where(&User{Name: "foo", Age: 20})
.Limit(10)
.Offset(5)
.Order("name ASC")
.First(&User{})
.ToSQL()
// SELECT * FROM "users" 
// WHERE "users"."name" = 'foo' AND "users"."age" = 20 AND "users"."deleted_at" IS NULL 
// ORDER BY name ASC,"users"."id" LIMIT 1 OFFSET 5
```
由于整套逻辑是保持用原来的流程和逻辑，所以能完整覆盖所有的查询场景，ToSQL 在 Find, Create, Save 之后能生成完整准确的 SQL 语句。

Add ToSQL support to generate SQL string.

---

schema/relationship.go
schema/relationship_test.go
tests/migrate_test.go

- Added a condition in the parse constraint in order to differentiate between a duplicate constraint (caused by a belongs-to and a has-many relationship between two models) and a self-referential belongs-to.
- There are probably many ways to make this check (perhaps checking the type of the relation instead of the whole object), so I would appreciate any feedback!
Addresses the concerns from #4372 (now able to create self-referential belongs-to constraints)

Fix self-referential belongs to constraint

---

clause/where.go
tests/named_argument_test.go

During the building of Where clauses, the NamedExpr type is omitted while determining whether the expression should be wrapped in parentheses. Therefore, although it is required, Where clauses containing both named arguments and OR conditions are not wrapped, and this causes the generation of different queries than desired. This pull request tries to fix this issue.
eg:
For the gorm statement below,
```go
db.Model(&User{}).Where("role = @role1 OR role = @role2",
map[string]interface{}{"role1": "admin", "role2": "super_admin"}).Find(&results)
```
the following query is generated.
~~~~sql
SELECT * FROM users WHERE role = 'admin' or role = 'super_admin' AND users.deleted_at IS NULL
~~~~
Due to the precedence of `AND` over `OR`, the query will be interpreted like
~~~~sql
`WHERE role = 'admin' …

Fix: Where clauses with named arguments may cause generation of unintended queries

---

clause/where.go
soft_delete.go
tests/soft_delete_test.go

- [] Tested
PR for https://github.com/go-gorm/gorm/issues/4914
- fix generate sql incorrect when use `soft_delete` and only one `or`
- 修复使用 `soft_delete` 并且仅有一个 `or` 时生成错误SQL.
Code:
```
func TestGORMorCondition(t *testing.T) {
user := User{Name: "jinzhu"}
DB.Create(&user)
ret := make([]*User, 0)
id := []uint32{1}
db := DB
for _, id := range id {
db = db.Or("id = ?", id)
}
db.Find(&ret)
}
```
SQL:
```
[0.125ms] [rows:1] SELECT * FROM `users` WHERE id = 1 OR `users`.`deleted_at` IS NULL
```

fix: generate sql incorrect when use soft_delete and only one OR

---

migrator/migrator.go
tests/migrate_test.go

Fix #4351 make migration column order predictable.

fix: auto migration column order unpredictable

---

finisher_api.go
tests/connection_test.go

- [×] Do only one thing
- [×] Non breaking API changes
- [×] Tested
- en : feat: add `Connection` to execute multiple commands in a single conn
- zh : 支持一个 conn 内可以执行多个命令
```
func TestWithSingleConnection(t *testing.T) {
var expectedName = "test"
var actualName string
setSQL, getSQL := getSetSQL(DB.Dialector.Name())
if len(setSQL) == 0 || len(getSQL) == 0 {
return
}
err := DB.Connection(func(tx *gorm.DB) error {
if err := tx.Exec(setSQL, expectedName).Error; err != nil {
return err
}
if err := tx.Raw(getSQL).Scan(&actualName).Error; err != nil {
return err
}
return nil
})
if err != nil {
t.Errorf(fmt.Sprintf("Connection should work, but got err %v", err))
}
if actualName != expectedName {
t.Errorf("Connection() method should get correct value, expect: %v, got %v", expectedName, …
```

feat: add `Connection` to execute multiple commands in a single conn

---

schema/field.go
schema/field_test.go
statement.go

1, time.Time, []byte type add alias support.
2, []byte alias type, fixed statement bind var parameter.
```go
func main() {        
type ID int64
type TIME time.Time
type BYTES []byte
type TypeAlias struct {
ID
TIME  `gorm:"column:ftime;type:timestamptz"`
BYTES `gorm:"column:fbytes;type:bytea"`
}
db, err := gorm.Open(postgres.New(postgres.Config{
DSN: `dsn`,
PreferSimpleProtocol: false,
}), &gorm.Config{
Logger:                 logger.Default.LogMode(logger.Info),
SkipDefaultTransaction: true,
})
if err != nil {
log.Fatal(err)
}
al := &TypeAlias{
ID:    2,
TIME:  TIME(time.Now()),
BYTES: []byte{1, 2, 3},
}
if err := db.AutoMigrate(al); err != nil {
t.Fatal(err)
}
if err := db.Create(al).Error; err != nil {
t.Fatal(err)
}
al1 := &TypeAlias{}
if err := db.First(al1).Error; err != nil { …
```

time.Time, []byte type add alias support. (rebase master)

---

callbacks/query.go
tests/connection_test.go
tests/joins_test.go

- [] Tested
omit not work when use join
```
func TestJoinWithOmit(t *testing.T) {
user := *GetUser("joins_with_omit", Config{Pets: 2})
DB.Save(&user)
results := make([]*User, 0)
if err := DB.Table("users").Omit("name").Where("users.name = ?", "joins_with_omit").Joins("left join pets on pets.user_id = users.id").Find(&results).Error; err != nil {
return
}
if len(results) != 2 || results[0].Name != "" || results[1].Name != "" {
t.Errorf("Should find all two pets with Join omit and should not find user's name, got %+v", results)
return
}
}
```

fix: omit not work when use join 

---

schema/naming.go
schema/naming_test.go

- [] Tested
-  en: fix replace empty table name result in panic.  if replaced name equal to `""` , should return name.
-  zh: 修复替换 table name 为空时会导致 panic.    如果替换后的 name 等于 `""` 就将 name 返回.
```
func TestReplaceEmptyTableName(t *testing.T) {
ns := NamingStrategy{
SingularTable: true,
NameReplacer:  strings.NewReplacer("Model", ""),
}
tableName := ns.TableName("Model")
if tableName != "Model" {
t.Errorf("invalid table name generated, got %v", tableName)
}
}
```

fix: replace empty table name result in panic

---

finisher_api.go

I find it very reassuring to know that after a finisher API, I get a clean db object for my next queries.
If you look at the example in https://gorm.io/docs you'd see many queries running one after the other.. but in reality they wouldn’t work in transaction.
That’s because in default mode, NewDB is false and will make all the clauses stay even after a finisher API.
My solution is just to have the value of the clone flag in the “parent” db object, be injected to its children transactions.
I have many usages of transactions around my code and many of them consist of multiple queries that aren't sharing the same clauses (e.g different `WHERE`).
So instead of having to use `db.begin().Session(gorm.Session{NewDB: true})` on each transaction, because :
A. it is verbose
B. It hurts …

Inherit clone flag (NewDB) on transaction creation

---

schema/naming.go
schema/naming_test.go
schema/relationship_test.go

This PR generates syntactically valid names for foreign key constraints when the table name is greater then 64 characters and the table name is schema-qualified, e.g. `my_schema.a_very_very_very_very_very_very_very_very_long_table_name`. 
Fixes https://github.com/go-gorm/gorm/issues/5029.
Previously the name formatter would leave `.` characters in the long schema-qualified table name intact. However, this generates an invalid foreign key constraint in Postgres and migrations fail with an error like this:
```
2022/01/26 17:14:17 Failed to auto migrate, but got error ERROR: syntax error at or near "." (SQLSTATE 42601)
```
The new behavior is for the `.` in the table name to be replaced with `_`.
The `.` to `_` translation was already occurring when the table name was less than 65 characters …

Fix invalid foreign key constraint name with long schema qualified tables

---

schema/serializer.go
tests/serializer_test.go

Implement a GobSerializer in schema/serializer to support Gob encoding in the latest released serializer tag feature. 
In the past, if we want to set the value of a struct into a certain field, we would marshal the struct to a string/bytes(normally with json/msgpack/gob). With the support for serializer, it becomes a relatively easy job. 
But now it only supports json and unixtime. Golang provide native support for gob, which has a better performance over json. Hopefully, this will help developers reduce the trouble on writing gob encoding and decoding.

feat: support gob serialize

---

scan.go
tests/query_test.go

The following error is throwed `destination not a pointer` when query single column into scanner .
close #5091

fix: query scanner in single column

---

gorm.go

ToSQL should always enable `SkipDefaultTransaction` regardless of current db.config.
An example of this change may improve performance
```
db, _ := gorm.Open(sqlite.Open("test.db"), &gorm.Config{SkipDefaultTransaction: false})
sql := DB.ToSQL(func(tx *gorm.DB) *gorm.DB {  
return tx.Clauses(clause.OnConflict{
Columns:   []clause.Column{{Name: "id"}},
DoUpdates: clause.AssignmentColumns([]string{"name", "age"}),
}).Create(&users)
})
```
The Create() call above will actually call `BeginTransaction` and `CommitOrRollbackTransaction` callbacks. But they are costly (involve connection handling) and not necessary in this case.

ToSQL should enable SkipDefaultTransaction by default

---

schema/index.go
schema/index_test.go

```
Name7        string `gorm:"index:type"``
```
call `AutoMigrate`,when index name is type, `parseFieldIndexes` will parse index TYPE is "TYPE", because `ParseTagSetting`'s params is `type`, it will return `map[TYPE]TYPE`,,so we should exclude index name in call `ParseTagSetting`'s params
error generate sql 
```
`CREATE INDEX `type` ON `xxxx`(`xxx`,`type`) USING TYPE`
```
```
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TYPE' at line 1", "elapsed": 0.000959069, "rows": 0, "sql": "CREATE INDEX `type` ON `xxxxxxxxx`(`xxxxx`,`type`) USING TYPE
```
https://github.com/go-gorm/playground/pull/446

fix when index name is "type", parseFieldIndexes will set index TYPE is "TYPE"

---

tests/query_test.go
utils/tests/utils.go

1. `AssertEqual` panic when `got` kind is `struct` but `expect` not.
2. when `got` and `expect` not `ConvertibleTo` at last, test case pass.
3. fix test case due to 2.
```go
...
// names is string slice ["pluck-user1","pluck-user2","pluck-user3"]
// sort.Reverse(sort.StringSlice(names2) result is interface ["pluck-user3","pluck-user2","pluck-user1"]
// but test pass
assertEqual(t, names, sort.Reverse(sort.StringSlice(names2)))
...
```

test: fix test case and utils

---

callbacks/associations.go
schema/naming.go

No feature changes, just pure coding style fix in the following two places:
1. callbacks/associations.go
`onConflictOption` function doesn't need the `selectColumns` param for its own logic, this is unused. Removing the param helps reduce memory cost.
2. schema/naming.go
`formatName` method would do a strings.Replace to get `formattedName`, the num for replacement is -1, which means ReplaceAll. So I change the strings.Replace method call to strings.ReplaceAll to make it more straightforward and understandable.

style: fix linter check problem for NamingStrategy and onConflictOption

---

migrator/column_type.go
tests/main_test.go
tests/migrate_test.go
tests/sql_builder_test.go
tests/upsert_test.go

No logic update.
Fix all typos in current repo with the help of [typos](https://github.com/crate-ci/typos).
Two exception:
- Column names such as `actived` in logger/sql_test.go remain the same as before to ensure compatibility.
- Variables defined in functions remain the same, such as `datas` in callbacks/preload.go.

style: fix coding typo

---

association.go
tests/associations_test.go

If Association Model missing primary field, it will execute sql like:
```sql
DELETE FROM `client_operators` WHERE client_id = 5 AND `client_operators`.`client_id` IN (NULL) AND `client_operators`.`operator_id` = 1
```
But if there is no primary field, we can't delete it, so we should throw an error.
close #5180

fix: throw err if association model miss primary key

---

.github/workflows/invalid_question.yml
.github/workflows/missing_playground.yml
.github/workflows/stale.yml
.github/workflows/tests.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

Set permissions for GitHub actions

---

scan.go
tests/joins_test.go

If there are more joins in the query, the scanIntoStruct function stops loading the data as soon as a null association is encountered. The test reproduces the case in question

Fix scanIntoStruct

---

finisher_api.go
tests/query_test.go

I think when the user uses `Offset` in `FindInBatches` the meaning is to skip the previous N records, and user uses `LIMIT` in `FindInBatches` the meaning is find total of N records.
close #5252

fix: FindInBatches with offset limit

---

migrator/migrator.go

Error check was missing in AutoMigrate.
Due to this miss, errors of underlying drivers might not be delivered, resulting in misleading error texts.
Example of such behavior is showed in https://github.com/go-gorm/gorm/issues/5282, which is ```duplicate column name: id``` but real error was in SQLite driver, namely ```invalid ddl```

fix missing error-check in AutoMigrate

---

schema/index.go
schema/index_test.go

In the issue #3973, if a struct with any composite indexes, these indexes will be invalid when the struct is embedded more than once. Because a composite index **must** specify its name, embedding more than once results in the duplicated name in db. Also if the name of index is specified manually, `NamingStrategy` will not be applied. Take the example of #3973:
```go
type Bar0 struct {
Foo
}
type Bar1 struct {
Foo
}
```
Both `Bar0` and `Bar1` will try to create an index of the same name `my_idx`. In this pull request, it provides a new field of index tag which is named to `composite`. It means the id of composite index. All fields which have the same composite id of the struct are put together to the same index, just like the original rule. But the improvement is it lets the most …

index: add composite id

---

migrator/migrator.go
tests/migrate_test.go

close #5300
This is because `dep.Schema.Table` and `d.Table`are not equal, `table` name `orders` but `users.dep.table` name `order_1`
https://github.com/go-gorm/gorm/blob/master/migrator/migrator.go#L793
https://github.com/go-gorm/gorm/blob/master/migrator/migrator.go#L809

fix: AutoMigrate with special table name

---

callbacks.go
tests/callbacks_test.go

When using multiple plugins, they may register different callbacks with `Before("*")` or `After("*")`, the order will be out of order.
current order
```go
createCallback.Before("*").Register("plugin_1_fn1", c1)
createCallback.After("*").Register("plugin_1_fn2", c2) //[c1 c2]
createCallback.Before("*").Register("plugin_2_fn1", c3)//[c1 c3 c2]
createCallback.After("*").Register("plugin_2_fn2", c4)//[c3 c1 c4 c2]
```

fix: callbcak sort when using multiple plugin

---

schema/relationship.go
schema/utils.go
tests/migrate_test.go

In many2many situation, `ownField` and `relField` cannot be resolved to primary keys, but are composite primary keys in the database.
This issues cause by field size and field database size not equal when they cannot be resolved to primary keys.
I don't know how to test in other driver and does only postgres have this problem, if so, maybe we can change [here](https://github.com/go-gorm/postgres/blob/master/migrator.go#L204) to `columnType.PrimaryKey()` 
close #5320

fix: many2many auto migrate

---

migrator/migrator.go
tests/migrate_test.go

quote index when creating table, just like CreateIndex
before
```mysql
CREATE TABLE `quoted_index_structs` (
`id` BIGINT UNSIGNED AUTO_INCREMENT,
`name` VARCHAR ( 255 ),
PRIMARY KEY ( `id` ),
INDEX AS ( `name` ) 
)
```
after
```mysql
CREATE TABLE `quoted_index_structs` (
`id` BIGINT UNSIGNED AUTO_INCREMENT,
`name` VARCHAR ( 255 ),
PRIMARY KEY ( `id` ),
INDEX `AS` ( `name` ) 
)
```

fix: quote index when creating table

---

clause/expression.go
clause/expression_test.go

Fixes https://github.com/go-gorm/gorm/issues/5355
If a named variable is followed by Windows CRLF style line endings, the variable name will include the \r portion of the line ending which causes the variable lookup in the namedMap to fail. In my PR, I've updated the expression builder to look for \r in addition to \n.

Fixed #5355 - Named variables don't work when followed by Windows CRLF line endings

---

tests/migrate_test.go
tests/tests_test.go

test for https://github.com/go-gorm/postgres/pull/109

test: test for skip prepared when auto migrate

---

scan.go
tests/scan_test.go

fix: duplicate column scan

---

finisher_api.go
tests/create_test.go

In FirstOrCreate, `result.Error` of `queryTx.Find` is not nil, but not assign to tx.Error.
I fixed `result.Error` assign to `tx.Error`.
https://github.com/ophum/gorm/blob/8edc4825256aa0dcc0f74bd3e92b7fc59ba09241/finisher_api.go#L319
when using a table that does not exist.

fixed FirstOrCreate not handled error when table is not exists

---

migrator/migrator.go
tests/migrate_test.go

relate to https://github.com/go-gorm/gorm/pull/5325 and https://github.com/go-gorm/mysql/pull/75
mariadb test will pass after https://github.com/go-gorm/mysql/pull/75 merged

fix: migrate column default value

---

scan.go
schema/field.go
tests/query_test.go

closes #5415 
closes #5414
Slice elem will reuse after #5388, so the null value should be updated, and we should change judge `relValue.IsNil()` in join.
Seems like a breaking change now, I'm not sure if revert is required as user-defined Serializers may also be affected

fix: reset null value in slice

---

migrator.go
migrator/index.go
migrator/migrator.go

feat: add method GetIndexes

---

schema/field.go
tests/serializer_test.go

fix serializer missing field when invoke scan
```
type CustomSerializer struct {
prefix []byte
}
func NewCustomSerializer(prefix string) *CustomSerializer {
return &CustomSerializer{prefix: []byte(prefix)}
}
func (c *CustomSerializer) Scan(ctx context.Context, field *schema.Field, dst reflect.Value, dbValue interface{}) (err error) {
switch value := dbValue.(type) {
case []byte:
err = field.Set(ctx, dst, bytes.TrimPrefix(value, c.prefix))
case string:
err = field.Set(ctx, dst, strings.TrimPrefix(value, string(c.prefix)))
default:
err = fmt.Errorf("unsupported data %#v", dbValue)
}
return err
}
```
invoke scan， prefix will be nil

fix:serializer contain field panic

---

migrator/migrator.go
tests/migrate_test.go

fix(MigrateColumn):declared different type without length

---

callbacks/associations.go
tests/associations_many2many_test.go
tests/migrate_test.go
tests/serializer_test.go

fix: association many2many duplicate elem

---

callbacks.go
finisher_api.go

Make transaction have before and after hooks, so plugin can hack before
or after transaction.
We hava a gorm plugin to handle database sharding. We save SaaS tenant info into context, then plugin can get the tenant in before hooks and determine which database shard to select. For now, `Transaction` api is not invoked through callbacks, we have to wrap gorm.ConnPool  as gorm.ConnPoolBeginner to select database.

feat: use callback to handle transaction

---

logger/sql.go

- [*] Do only one thing
- [*] Non breaking API changes
- [*] Tested
This fix #5520 . It used to loop N (number of vars) times to do replace while logging sql. This has very bad performance for bulk creating.
This PR change it to O(1) by using `regexp.ReplaceAllStringFunc`.
Bulk create with postgres driver and log enabled.

fix bad logging performance of bulk create (#5520)

---

schema/field.go
schema/serializer.go
tests/go.mod
tests/serializer_test.go

- [✅] Do only one thing
- [✅] Non breaking API changes
- [✅] Tested
修复了 #5524 issue

fix: empty serilizer err #5524

---

finisher_api.go

gorm's Delete() method performs either a soft or hard delete, depending on whether the passed data model includes a `deletedAt` field.  This is detailed [here in the docs](https://gorm.io/docs/delete.html#Soft-Delete) and this PR adds this to the Godoc comment.
I've also cleaned up the grammar to make the language of the comment consistent.
As a new user to gorm I found myself referencing the external docs at gorm.io to learn the behaviour of this method.  Adding key details to inline documentation improves the user experience.
If there is an appetite for contribution to documentation I would like to submit more PRs like this across the codebase.

Update Delete Godoc to describe soft delete behaviour

---

statement_test.go

redundant type from array, slice, or map composite literal.
N/A

Refactor: redundant type from composite literal

---

go.mod
logger/logger.go
tests/go.mod

`"io/ioutil"` has been deprecated since Go 1.16.
https://tip.golang.org/doc/go1.16#ioutil
N/A

Replace `ioutil.Discard` with `io.Discard`

---

migrator/migrator.go
statement.go
tests/upsert_test.go

simplified regexp

---

finisher_api.go

This PR contains a general rewrite of the method Godocs in `finisher_api.go`, including:
* Fix grammar & spelling, improve wording
* Employ consistent language across all documentation
* Explicitly reference method parameters in comments
* Fill gaps in explanations
* I've used existing documentation from gorm.io when available
* when not available I've done my best to write my own description of what the method does
* limit line length to 120 chars
This will improve usability of GORM by providing enhanced inline documentation

Rewrite of finisher_api Godocs

---

migrator/migrator.go
tests/postgres_test.go

Fix bug: `AutoMigrate()` doesn't update check constraints if there is no relationship constraints.
`AutoMigrate()` updates check constraints, no matter there are relationship constraints or not.

AutoMigrate() should always migrate checks, even there is no relationship constraints.

---

migrator/migrator.go
tests/migrate_test.go

close #5702
The field name is not unique, only the db name is, we need to hit the db name in the LookUpField.

fix(migrate): same embedded filed name

---

scan.go
tests/query_test.go

related to https://github.com/go-gorm/gorm/issues/5621

fix: scan array

---

schema/schema.go
tests/postgres_test.go

Returning the ID which has uuid.UUID or String type after created
I have a sql script like the below and run on Postgres DB:
```sql
CREATE TABLE "users" (
"id" UUID NOT NULL DEFAULT gen_random_uuid(),
"email" TEXT NOT NULL,
"password" TEXT,
"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updated_at" TIMESTAMP(3) NOT NULL,
"deleted_at" TIMESTAMP(3),
CONSTRAINT "users_pkey" primary KEY ("id")
);
```
In the golang code, I created a struct like this:
```go
ID        uuid.UUID      `json:"id"`
Email     string         `json:"email"`
Password  string         `json:"password"`
CreatedAt time.Time      `json:"created_at"`
UpdatedAt time.Time      `json:"updated_at"`
DeletedAt gorm.DeletedAt `json:"deleted_at"`
}
```
I use this method to create user:
```go
user := …
```

fix: return id which have type string after created

---

gorm.go
prepare_stmt.go
tests/prepared_stmt_test.go

fix: prepare deadlock

---

clause/on_conflict.go
tests/postgres_test.go

Fix https://github.com/go-gorm/gorm/issues/5713
If `OnConstraint ` is specified in `clause.OnConflict`, just ignore the columns and `where target` configs. Follow the [document](https://www.postgresql.org/docs/15/sql-insert.html), something like `ON CONFLICT xx ON CONSTRAINT yy` is invalid.

Fix OnConstraint builder

---

schema/relationship.go

fix: primaryFields are overwritten

---

chainable_api.go
clause/benchmarks_test.go
clause/limit.go
clause/limit_test.go
finisher_api.go

fix: limit=0 results (#5735)

---

callbacks/associations.go
tests/associations_test.go

close https://github.com/go-gorm/gorm/issues/5754

fix: association without pks

---

prepare_stmt.go
tests/prepared_stmt_test.go

feat(PreparedStmtDB): support reset

---

tests/migrate_test.go

related to https://github.com/go-gorm/postgres/pull/137

test: invalid cache plan with prepare stmt

---

clause/joins.go
clause/joins_test.go

test(clause/joins): add join unit test

---

utils/utils_test.go

test(utils): add utils unit test

---

utils/utils.go
utils/utils_unix_test.go
utils/utils_windows_test.go

To fix logger path bug.
before:
``` shell
➜  app go run .
2022/11/04 21:10:29 /Users/kvii/go/pkg/mod/gorm.io/gorm@v1.24.1/callbacks.go:134
[0.004ms] [rows:0] SELECT 1
```
after:
``` shell
➜  app go run .
2022/11/04 20:58:48 /Users/kvii/workspace/qs/gormt/app/main.go:14
[0.005ms] [rows:0] SELECT 1
```

fix logger path bug

---

finisher_api.go
tests/query_test.go

fix(FindInBatches): throw err if pk not exists

---

schema/schema.go
tests/associations_belongs_to_test.go

fix: skip append relation field to default db value

---

scan.go
tests/embedded_struct_test.go

Adds a testcase for embedded fields when selecting multiple row values. Current behaviour returns the last row value for the embbed ptr to all the structs.
Adds a testcase currently. Looking into the issue.
```
--- FAIL: TestEmbeddedStruct (0.01s)
embedded_struct_test.go:92: 0 &{ George }
embedded_struct_test.go:94: expected author Edward got George
embedded_struct_test.go:92: 1 &{ George }
```
Fix embedded struct ptrs. Reverted the optimisation for reusing structs here: https://github.com/go-gorm/gorm/pull/5388

Add test case for embedded value selects

---

chainable_api.go
finisher_api.go

No code changes, only comments.
Add comments to functions in chainable_api. Depending on the method, these comments add some additional context or details that are relevant when reading the function, link to the actual docs at gorm.io/docs, or provide examples of use. These comments should make GORM much more pleasant to use with an IDE that provides hoverable comments, and are minimal examples.
Also add in-code documentation to FirstOrInit and FirstOrCreate.
Almost all examples are directly pulled from the docs, with short comments explaining the code. Most examples omit the `db.Model(&User{})` for brevity, and would not actually work.
As a user using GORM, having small examples and more thorough hover comments allows me to write simple code without having to reference an external …

Update func comments in chainable_api and FirstOr_

---

migrator/migrator.go

Print SQL in AutoMigrate with DryRun option.
As mentioned in #3545.

DryRun for migrator

---

gorm.go
migrator/migrator.go
tests/migrate_test.go

fix #5913 
`DB.AutoMigrate` migrates related tables automatically, which is unexpected.
So I add a `IgnoreRelationshipsWhenMigrating` configuration to disable it. And make `-:migration` work properly on relationship fields.

fix(migrator): ignore relationships when migrating #5913

---

migrator/migrator.go
tests/migrate_test.go

fix #5953 
Tag `default:'null'` is treated as same as `default:null` when migrating.

fix(migrator): Tag default:'null' always causes field migration #5953

---

soft_delete.go
tests/soft_delete_test.go
tests/tests_test.go

```
type Book struct {
ID        uint
Pages     uint
DeletedAt gorm.DeletedAt `gorm:"zeroValue:'1970-01-01 00:00:01'"`
}
```
it may be necessary for us to set the type of delete_at datetime. and if delete_at is null, we can not add it into the composite index. so we can use 1970-01-01 00:00:01 (or other values you like)as zero value.
if we query books, gorm can generate the sql automatically
```
select * from books where delete_at = '1970-01-01 00:00:01'
```
if we delete books, gorm can generate the sql automatically
```
update books set  delete_at = 'xx' where delete_at = '1970-01-01 00:00:01'
```

fix: support zeroValue tag on DeletedAt

---

.github/workflows/tests.yml
tests/associations_belongs_to_test.go
tests/associations_many2many_test.go
tests/associations_test.go
tests/docker-compose.yml
tests/go.mod
tests/helper_test.go
tests/migrate_test.go
tests/sql_builder_test.go
tests/tests_all.sh
tests/tests_test.go

Add TiDB integration test cases. And skip some features that TiDB is not implicated.
This PR is based on https://github.com/go-gorm/mysql/pull/105, need to wait for that to merge.

feat: add tidb integration test cases

---

callbacks/query.go
clause/select_test.go
migrator/migrator.go
model.go
schema/field.go
schema/relationship.go
schema/serializer.go
tests/connpool_test.go
tests/embedded_struct_test.go
tests/helper_test.go
tests/migrate_test.go
tests/preload_test.go
tests/table_test.go

See https://github.com/go-gorm/gorm/issues/6054
Fixed use of `Unscoped()` on `Preload(..)`.
Retrieval of models with `Unscoped()` and `Preload(..)` does not include soft-deleted records.
Use of `Unscoped()` should [include](https://gorm.io/docs/delete.html#Find-soft-deleted-records) soft-deleted records.

Issue 6054: Unscoped not working with PreLoad on Joins

---

association.go
tests/associations_many2many_test.go

Fix bug when association concurrently appending.
`Association` in each goroutine will modify the user.Languages by `reflect.Append`, which method grows the slice.
If it grows successfully,  languages will be a new slice, that's ok.
But If cap is enough, these goroutines will write the same slice, that's wrong.
If we only call `DB.FirstOrCreate(&user)`, user.Languages len is 0 and cap is 0, that's ok.
if we only call `DB.Preload("Languages").FirstOrCreate(&user)`, still len 0 and cap 0.
But we call `DB.FirstOrCreate(&user)` first, then `DB.Preload("Languages").FirstOrCreate(&user)`, user.Languages is len 0 and cap 10, this error will occur #5801
```go
DB.FirstOrCreate(&user)
DB.Preload("Languages").FirstOrCreate(&user)
var wg sync.WaitGroup
for i := 0; i < count; i++ {
wg.Add(1)
go …
```

fix: association concurrently appending

---

tests/docker-compose.yml

quotes on docker-compose.yml ports
https://docs.docker.com/compose/compose-file/compose-file-v3/#ports
> When mapping ports in the HOST:CONTAINER format, you may experience erroneous results when using a container port lower than 60, because YAML parses numbers in the format xx:yy as a base-60 value. For this reason, we recommend always explicitly specifying your port mappings as strings.

quotes on docker-compose.yml ports

---

errors.go
migrator.go
migrator/migrator.go
tests/migrate_test.go

create view #4966 
It's different from issue's suggestion.
I found the unimplemented `CreateView` function in `Migrator`,
then I implemented it.
About `ViewOption`:
- `Query` is a [subquey](https://gorm.io/docs/advanced_query.html#SubQuery)
- If `Replace` is true, exec `CREATE OR REPLACE`. sqlite may not support this.
- If `CheckOption` is not empty, append to sql, e.g. `WITH LOCAL CHECK OPTION`
```go
DB.Migrator().CreateView("users_pets", gorm.ViewOption{Query: DB.Model(&User{}).Select("users.id, users.name")})
```
```sql
CREATE VIEW `users_pets` AS SELECT users.id, users.name FROM `users`
```

Create and drop view

---

schema/schema.go
schema/schema_test.go
tests/create_test.go

Fix #4930 workaround for databases that support auto-increment in composite primary key.
Fix issue https://github.com/go-gorm/gorm/issues/4930
In MySQL, you can have composite primary key with auto-increment 
For example:
https://github.com/nash90/playground/blob/7a82d16b1b1b626df01cf43089b302de7c2a6bd9/models.go#L63-L70
```go
type CompositeKeyProduct struct {
ProductPointID int       `gorm:"primaryKey;autoIncrement:true;column:product_point_id"`
LanguageCode   int       `gorm:"primaryKey;autoIncrement:false;column:language_code"`
Code           string    `gorm:"column:code"`
Name           string    `gorm:"column:name"`
CreatedAt      time.Time `gorm:"column:created_at"`
UpdatedAt      time.Time `gorm:"column:updated_at"`
}
```
Upon insert new record into `CompositeKeyProduct` with the …

Fix: Composite primary key with auto-increment value returns 0 after insert

---

callbacks/query.go
scan.go
tests/joins_test.go
utils/tests/utils.go
utils/utils.go

feat: support nested join

---

finisher_api.go
tests/update_test.go

Save should be idempotent. #6139 #6134 
When call `Save` twice with the same object, `Save` should not raise an error.
```golang
var company Company
DB.Frist(&company)
DB.Save(&company)
DB.Save(&company) // should not create new record or rasise an error.
DB.Save(&company) // should not create new record or rasise an error.
```

save should be idempotent

---

finisher_api.go
tests/count_test.go

First created in #4560 and #4809 and fixed in #4885
But due to the modification at f91313436abcfe7a28a488d5d6777b31a94f24fb, it reappeared.
close #6157.
When `Count` with `Group`, It should return the number of groups

fix: count with group (#6157)

---

finisher_api.go

avoid starting a transaction when performing only one insert operatio…
avoid starting a transaction when performing only one insert operation in CreateInBatches

avoid starting a transaction when performing only one insert operation in CreateInBatches

---

gorm.go
tests/error_translator_test.go

This will enable the Translate Error feature to have backward compatibility with old gorm versions.

refactor: translatorError flag added for backward compatibility

---

schema/field.go
tests/embedded_struct_test.go

closes https://github.com/go-gorm/gorm/issues/5431
#5388 has been revert by #5901
Now we should revert #5417

fix: embedded should be nil if not exists

---

clause/limit.go
clause/limit_test.go

fix for issue https://github.com/go-gorm/gorm/issues/6188#issue-1641432003
when execute `db.Limit(0).Offset(0).Where("id > ?", 10).Find(&users)`, it will return all data satified where condition. Namely, sql generated is `select * from users where id > 10`, but not `select * from users where id > 10 limit 0`, which is diff from sql semantics.

fix: `limit(0).offset(b)` return all data, where b <= 0

---

migrator/index.go
migrator/migrator.go

refactor(migrator): non-standard codes

---

callbacks/associations.go
tests/associations_many2many_test.go

Extends https://github.com/go-gorm/gorm/pull/5473 to `many2many` models with `belongs to` associations.
Using the following models that have `many2many` and `belongs to` associations:
```
type Application struct {
ID        string `gorm:"primarykey"`
Resources []Resource 
}
type Resource struct {
ID       string `gorm:"primarykey"`
Name     string
OwnerId  string
Owner    Owner 
}
type Owner struct {
ID   string `gorm:"primarykey"`
Name string
}
```
In cases where two resources share the same `Owner`, attempting to update an `Application` using `FullSaveAssociations: true` will result in an error. GORM tries to insert the same `Owner` multiple times in a single INSERT command: 
```
INSERT INTO "owner" ("id","name") VALUES ('1','owner-1'),('1','owner-1') ON CONFLICT ("id") …
```

fix: many2many association with duplicate belongs to elem

---

callbacks.go
chainable_api.go
migrator.go
statement.go
tests/scopes_test.go

fix conditions in `Scope` #6148 
```go
DB.Table("test").Scopes(
func(d *gorm.DB) *gorm.DB {
return d.Where("a = 1")
},
func(d *gorm.DB) *gorm.DB {
return d.Where(d.Or("b = 2").Or("c = 3"))
},
).Rows()
```
It should be:
```sql
SELECT * FROM `test` WHERE a = 1 AND (b = 2 OR c = 3)
```
But now it is:
```sql
SELECT * FROM `test` WHERE a = 1 OR b = 2 OR c = 3 AND (a = 1 OR b = 2 OR c = 3)
```

fix cond in scopes

---

gorm.go

When calling `gorm.Open`, there is the following code:
```go
if config.Dialector != nil {
err = config.Dialector.Initialize(db)
}
``` 
`config.Dialector.Initialize(db)` typically calls [`sql.OpenDB`][sql-opendb] to create an `*sql.DB`, and starts an goroutine `db.connectionOpener(ctx)`.
Next, a typical database driver will attempt to connect to the schema specified in the DSN. If an error occurs at this time (such as the specified schema not existing), it will cause `config.Dialector.Initialize(db)` to return an error. However, after receiving this error, GORM does not attempt to close `*sql.DB`. This causes the `db.connectionOpener(ctx)` goroutine to leak.
In my scenario, I used the wrong schema and retried calling `gorm.Open` multiple times. By observing the dumped goroutine, I found …

fix: avoid coroutine leaks when the dialecter initialization fails.

---

callbacks.go

EN:
use stable sort algorithm to replace unstable sort 
Registing multi plugins, but when execute Create mode, plugin executed order is not meet expectations.
---
中文：
使用sort的稳定排序替换不稳定排序。
ctx:注册多个插件；
对插件进行排序后，插件的执行顺序会发生改变，导致一些重要的插件位置发生了变更，导致预期之外的结果。

fix: use slice Stale sort

---

schema/field.go
tests/embedded_struct_test.go

fix #6288 
some numeric types in embedded pointer type struct cause test failed
(types that other than int64, uint64, float64)

fix: 🐛 some numeric types in embedded pointer type struct cause test failed

---

migrator.go
migrator/migrator.go
migrator/table_type.go
tests/tests_all.sh

migrator support table comment.
1. [https://github.com/go-gorm/gorm/pull/6225](https://github.com/go-gorm/gorm/pull/6225)
2. [https://github.com/go-gorm/mysql/pull/114](https://github.com/go-gorm/mysql/pull/114)
3. [https://github.com/go-gorm/gen/pull/822](https://github.com/go-gorm/gen/pull/822)

feat: migrator support table comment

---

schema/field.go
tests/embedded_struct_test.go

Refer to https://github.com/go-gorm/gorm/issues/6288
Fix embedded struct with custom datatypes and *time.time will failed the test.
Test should pass.

fix: 🐛 embedded struct test failed with custom datatypes

---

finisher_api.go

return err if the query exceed single select sql memory limit. [#6277 ](https://github.com/go-gorm/gorm/issues/6277)
```go
Name     string
Age      uint64
Birthday string
Account  string
Company  string
}
func TestGORM(t *testing.T) {
// append data
user := User{
Name:     "ddddddddddddddddddddddddddddddddfsfdsfsd",
Age:      0,
Birthday: "dbdfbbbbbbbbbbbbbbbbbbbbbbbbbdfgfdgfdg",
Account:  "apoiorpqwifpofpwiefpiweopfioeifoeifpwifpewifpwifpewifpewifpweifpiwefpiwepfiwpeifpwiefpiwe",
Company:  "apoiorpqwifpofpwiefpiweopfioeifoeifpwifpewifpwifpewifpewifpweifpiwefpiwepfiwpeifpwiefpiweapoiorpqwifpofpwiefpiweopfioeifoeifpwifpewifpwifpewifpewifpweifpiwefpiwepfiwpeifpwiefpiweapoiorpqwifpofpwiefpiweopfioeifoeifpwifpewifpwifpewifpewifpweifpiwefpiwepfiwpeifpwiefpiweapoiorpqwifpofpwi …
```

fix:clickhouse error not capture(#6277)

---

errors.go

- [Y ] Do only one thing
- [ Y] Non breaking API changes
- [ Y] Tested
Updated the translator and added the support of "foreign key constraint violation". For this, this error type is needed here.
Lets say I have a struct RoleAssignment having RoleID as a foreign key
```
type RoleAssignment struct {
RoleID      int         `gorm:"type:INTEGER;NOT NULL"`
Locations   string      `gorm:"type:VARCHAR(255);NOT NULL"`
SubjectID   int         `gorm:"type:INTEGER;NOT NULL"`
SubjectType SubjectType `gorm:"type:VARCHAR(255);NOT NULL"`
Role        Role
}
```
and I want to insert a record having role_id which does not exist in Role table, here gorm is throwing pgerror which should be translated to gorm error. As suggested below:
```
result := tx.Create(&roleAssignment)
if result.Error != nil {
if …
```

Added support of "Violates Foreign Key Constraint"

---

finisher_api.go
tests/transaction_test.go

fix(nested transaction): SavePoint SQL Statement not support in Prepared Statements
Nested transactions are implemented through savepoint, but savepoint does not support precompiled statements, and if the session is enabled for precompilation, nested transactions will fail

fix(nested transaction): SavePoint SQL Statement not support in Prepared Statements

---

finisher_api.go
tests/update_test.go

Hook is executed twice in `Save` func, close #6285 
```go
type Token struct {
ID  int
Content string `gorm:"type:varchar(100)"`
}
func (t *Token) BeforeSave(tx *gorm.DB) error {
t.Content += "_encrypted"
return nil
}
token := Token{Content: "token"}
DB.Save(&token) // "token_encrypted"
token = Token{
ID:           token.ID,
Content: "token"
}
DB.Save(&token) // mysql RowsAffected is 0, it should be "token_encrypted" instead of "token_encrypted_encrypted"
```

fix: save with hook (#6285)

---

prepare_stmt.go

fix begin transaction fail, rollback panic
```go
tx = db.Begin()  // when begin error
err := tx.Where(sql).Update(m).Err
if err = nil{
tx.Rollback()   // will panic
return err
}
tx.Commit()
```

fix: begin transaction fail, rollback panic

---

gorm.go
tests/gorm_test.go

When the open fails (e.g. wrong loc), gorm try to close `sql.db`.  #6249
But db may be nil, we should avoid panic. 
Close #6359

fix: avoid panic when open fails

---

gorm.go
prepare_stmt.go

This PR removes unnecessary allocation of prepared statements when initializing a database connection.

refactor: remove unnecessary prepared statement allocation

---

gorm.go

This pull request addresses a bug that caused a panic when connecting to the database using an incorrect DSN. The bug has already been fixed in this commit (https://github.com/go-gorm/gorm/commit/c1ea73036715018a1bb55cdb8690441044e13a76). However, to prevent potential future bugs, I have refactored the code to include null detection during type assertion.
https://github.com/go-gorm/gorm/blob/c1ea73036715018a1bb55cdb8690441044e13a76/gorm.go#L374-L387
Before merging this PR (c1ea730), `connPool.(*sql.DB)` returned `nil, nil` which had a negative impact on the called method.

reafactor: add nil detection when sqldb return

---

tests/scanner_valuer_test.go

Documentation for [`database/sql.Scanner`](https://pkg.go.dev/database/sql#Scanner) states that `Scan(src)` should not retain (i.e. it should *copy*) the `src` argument.
```go
// Reference types such as []byte are only valid until the next call to Scan
// and should not be retained. Their underlying memory is owned by the driver.
// If retention is necessary, copy their values before the next call to Scan.
```
This becomes an issue for this test if a driver returns a slice that is invalidated by [`rows.Close()`](sql#Rows.Close).
Copying the slice fixes this test failing with my [SQLite driver](https://github.com/ncruces/go-sqlite3).

fix: database/sql.Scanner should not retain references

---

utils/tests/models.go

Fixes an incorrect documentation comment. The comment says "NamedPet is a reference to a Named `Pets` (has many)", but it's actually a reference to a single Pet (`NamedPet  *Pet`)

Fix incorrect documentation comment (has many -> has one)

---

tests/associations_many2many_test.go
tests/error_translator_test.go
tests/go.mod
tests/prepared_stmt_test.go
tests/tests_test.go
tests/transaction_test.go

Test coverage for ErrDuplicatedKey, related issue: https://github.com/go-gorm/gorm/issues/6345

test: coverage for duplicated key err

---

.github/workflows/tests.yml

As of latest image for mariadb the mysqladmin command is gone. we should use mariadb-admin instead.
https://github.com/MariaDB/mariadb-docker/issues/512

ci: fix mariadb mysqladmin

---

tests/error_translator_test.go
tests/go.mod
tests/tests_test.go

Test coverage for ErrForeignKeyViolated, related issue: https://github.com/go-gorm/gorm/issues/6345

test: coverage for foreign key violation err

---

logger/sql.go
logger/sql_test.go

ExplainSQL's handling of floating point numbers, which were previously formatted like .6f, this PR uses strconv.FormatFloat to format them to preserve precision
An arbitrary floating point number with more than 6 decimal places, for example: 0.1753607109

keep float precision in ExplainSQL

---

gorm.go

When the `Session` method is invoked with `&gorm.Session{NewDB: true, SkipHooks: true}` object, it ignores the `SkipHooks`. This PR adds the `SkipHooks` in `getInstance` method.
```go
// This will still call the associated hook currently. With this PR, hooks associated will not be called in this case.
db.Session(&gorm.Session{NewDB: true, SkipHooks: true}).First(&sampleObj)
```

fix: rectify `SkipHooks` not working with `NewDB` set in Session method

---

clause/expression.go
clause/expression_test.go

when the value of `clause.Eq` is an empty array, the SQL should be `IN (NULL)`

fix(clause): clause equal empty array

---

go.sum
gorm.go
interfaces.go
prepare_stmt.go

feat: rm GetDBConnWithContext method

---

logger/sql_test.go

add float32 tset case for sql_test.go logger.ExplainSQL func 
add float32 test case for `height` field
relate pr is https://github.com/go-gorm/gorm/pull/6495

add float32 test case for  keep float precision in ExplainSQL

---

gorm.go

Dialector initialize error leads to closing DB connection. However if DB connection is not even created, code inside gorm provides `nil` as an error even though `db` doesn't exist (is nil), so it tries to close what can't be closed and results to panic.
`panic: runtime error: invalid memory address or nil pointer dereference`
This fix now doesn't attempt to close non-existant database connection and instead continues, so the proper error is shown.
When I provide this example DSN (I am aware that this is wrong, it's a purpose to showcase this problem):
`test:test@localhost/test?charset=utf8mb4&parseTime=True&loc=Local`
To this piece of code:
`db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})`
I got:
`panic: runtime error: invalid memory address or nil pointer dereference`
With this fix …

Fixed error message when dialector fails to initialize

---

migrator/migrator.go
tests/go.mod
tests/migrate_test.go

Fix #4760. Currently, sqlite dialector can't apply `AUTOINCREMENT` to the field type. The reason this method cannot work is if a field is marked as `AutoIncrement` and `PrimaryKey` at the same time, when we apply `AUTOINCREMENT` to data type, it will create SQL like the following:
```sql
CREATE TABLE `example_table` (`id` integer PRIMARY KEY AUTOINCREMENT, ..., PRIMARY KEY (`id`))'
```
This can cause `SQL logic error: table "example_table" has more than one primary key (1)` error, because there is two `PRIMARY KEY` definition in this statement. The root cause is `hasPrimaryKeyInDataType` doesn't check the result of `Dialector.DataTypeOf` method.
By checking the result of `Dialector.DataTypeOf` method, a dialector can define its behavior for `AUTOINCREMENT & PRIMARY KEY` situation.
The …

fix: sqlite dialector cannot apply `PRIMARY KEY AUTOINCREMENT` type

---

clause/expression.go

1. https://github.com/go-gorm/gorm/blob/master/clause/expression.go#L124
The pre-alocate name is not used
2. https://github.com/go-gorm/gorm/blob/master/clause/expression.go#L129C4-L129C8 
The space of the previous time can be reused

feat: reuse name

---

utils/utils.go
utils/utils_test.go

I got the following panic
```
panic: value method gorm.io/datatypes.JSON.Value called using nil *JSON pointer
goroutine 134 [running]:
gorm.io/datatypes.(*JSON).Value(0x135c7c0?)
<autogenerated>:1 +0x56
gorm.io/gorm/utils.AssertEqual({0x135c7c0, 0xc0007e06f0}, {0x135c7c0, 0x0})
/home/mgoeppe/go/pkg/mod/gorm.io/gorm@v1.25.2/utils/utils.go:99 +0x9f
gorm.io/gorm.(*Statement).Changed.func1(0xc0003eaf00)
/home/mgoeppe/go/pkg/mod/gorm.io/gorm@v1.25.2/statement.go:643 +0x251
gorm.io/gorm.(*Statement).Changed(0xc0007e4a80, {0xc00079c4c8, 0x1, 0x41123d?})
/home/mgoeppe/go/pkg/mod/gorm.io/gorm@v1.25.2/statement.go:658 +0x298
```
when using a `*datatypes.JSON` model field where the *datatypes.JSON is not nil but refers to a []byte which is nil. The panic is raised when valuer.Value() is called. …

*datatypes.JSON in model causes panic on tx.Statement.Changed

---

schema/schema.go

Go 1.22 goes somewhat toward addressing the issue using reflect MethodByName disabling linker deadcode elimination (DCE) and the resultant large increase in binary size because the linker cannot prune unused code because it might be reached via reflection.
Go Issue https://github.com/golang/go/issues/62257 reduces the number of incidences of this problem by leveraging a compiler assist to avoid marking functions containing calls to MethodByName as ReflectMethods as long as the arguments are constants. 
An analysis of Uber Technologies code base however shows that a number of transitive imports still contain calls to MethodByName with a variable argument, including GORM.
In the case of GORM, the solution we are proposing is because the number of possible methods is finite, we will "unroll" …

Don't call MethodByName with a variable arg

---

tests/delete_test.go
tests/update_test.go

Add sqlserver to the list of dialectors that support update returning and delete returning. This is possible thanks to https://github.com/go-gorm/sqlserver/pull/116. The new tests will not work until we use the new version of the sqlserver dialector but I don't know what flow do you follow in this case

Add support for returning in sqlserver

---

tests/tests_test.go

As of now, the Foreign Key constraint is [OFF](https://www.sqlite.org/pragma.html#pragma_foreign_keys) by default in ```sqlite3```.
In GORM ```tests``` package the constraint is enabled by running following code:
https://github.com/go-gorm/gorm/blob/6bef318891b98263f3568c13093b5860245d2c52/tests/tests_test.go#L46-L48
for the global ```DB``` instance.
The problem is that this code is executed once inside ```init```, thus leaving other calls to ```OpenTestConnection``` not executing the same logic.
The code should be moved inside ```OpenTestConnection```, since some tests do not use the global ```DB``` instance, preferring to call ```OpenTestConnection``` for their own purpose.
The issue was solved the wrong way in https://github.com/go-gorm/gorm/commit/c10f807d3c0b2b3204c80d62cf7650e21d7e33 …

tests for sqilte: enable FOREIGN_KEYS inside OpenTestConnection

---

migrator.go
migrator/migrator.go
schema/naming.go
tests/associations_belongs_to_test.go
tests/count_test.go
tests/preload_test.go
tests/update_test.go

It's a part of https://github.com/go-gorm/gorm/pull/6386.
Defining new methods for use in drivers

feat: add MigrateColumnUnique

---

logger/logger.go

chore(logger): optimize

---

callbacks/create.go
schema/field.go
tests/create_test.go

- 
This pull request aims to support returning the primary key value, when using a map (or map list) to call GORM to insert record, in auto-increment primary key case. 
If the primary key value is not set, the returned map or map list will be filled with a custom column "@id".
The following cases are all using **auto-increment primary key**
**Case 1:**
&ensp; Input: map or map list without primary key
&ensp; Output: map or map list will be filled with "@id"
**Case 2:**
&ensp; Input: map or map list with primary key
&ensp; Output: map or map list will be filled with "@id"
The following cases are all using **non-auto-increment primary key**
**Case 1:**
&ensp; Input: map or map list without primary key
&ensp; Output: error, the same as before.
**Case 2:**
&ensp; Input: map or map list with …

map insert support return increment id

---

clause/locking.go
clause/locking_test.go

This PR provides constants for locking strength and locking option to make it easier to "guess". Partially solves https://github.com/go-gorm/gorm/issues/6720
```
db.Clauses(clause.Locking{
Strength: clause.LockingStrengthUpdate,
Options: clause.LockingOptionsNoWait,
}).Find(&users)
```

Making locking parameters more intuitive

---

schema/relationship.go
schema/relationship_test.go
tests/associations_has_many_test.go
tests/helper_test.go
tests/migrate_test.go
tests/tests_test.go
utils/tests/models.go

This pull request enables users to customize the type and id column names for polymorphic associations in GORM.
Previously, polymorphic associations were limited to default naming conventions (`<type>_Type` and `<type>_ID`).
Users can now specify custom type and id column names for polymorphic associations, offering greater adaptability to diverse database schemas.
close #6717

feature: bring custom type and id column name to polymorphism

---

statement.go
statement_test.go

- [ x ] Do only one thing
- [ x ] Non breaking API changes
- [ x ] Tested
Fixes bug:
Code:
```go
db.InnerJoins("User.Company", db.Select("User__Company.*")).Take(&order)
```
Expected:
```sql
SELECT order.id, order.time, ..., User__Company.id, User__Company.name, User_Company... FROM ...
```
Actually before:
```sql
SELECT order.id, order.time, order... FROM
```

fix: join and select mytable.* not working

---

logger/sql.go
logger/sql_test.go

[`logger.ExplainSQL`](https://github.com/iTanken/gorm/blob/dc066a1d5637a60eb25d897411753b837b3a2b4f/logger/sql.go#L38) using consecutive pairs of escaper in SQL string represents an escaper, preventing it from being interpreted as the string terminator. This is a widely used escape mechanism in SQL standards and is applicable in most relational databases.
https://github.com/go-gorm/postgres/issues/236
https://github.com/go-gorm/playground/pull/677

fix: ExplainSQL using consecutive pairs of escaper in SQL string represents an escaper

---

utils/utils.go

When using gen, the logger always print the caller from xxx.gen.go, this is not convenient for user to debug.
There is an issue also mention this problem #6697.
After ignore this suffix, we can get the real caller in our project from log.

fix: ignore .gen.go suffix in logger to get the real caller when using gen

---

callbacks/preload.go
callbacks/query.go
tests/preload_test.go

Fix the issue #6715, preload shouldn't overwrite the value of join.
See https://github.com/go-gorm/gorm/issues/6715#issuecomment-1873581676
```go
type (
Preload struct {
ID       uint
Value    string
NestedID uint
}
Join struct {
ID       uint
Value    string
NestedID uint
}
Nested struct {
ID       uint
Preloads []*Preload
Join     Join
ValueID  uint
}
Value struct {
ID     uint
Name   string
Nested Nested
}
)
DB.Joins("Nested").Joins("Nested.Join").Preload("Nested.Preloads").First(&find)
```

fix: preload shouldn't overwrite the value of join

---

migrator/migrator.go
tests/go.mod
tests/migrate_test.go

It's part 2 of #6386 which is the part of rollback, see https://github.com/go-gorm/gorm/pull/6386#issuecomment-1820049165.
It will also fix the ci.
But note that it depends on 
- https://github.com/go-gorm/mysql/pull/123
- https://github.com/go-gorm/postgres/pull/195
- https://github.com/go-gorm/sqlite/pull/156
- https://github.com/go-gorm/sqlserver/pull/106
After the above requests is merged, this pr still needs to update tests/go.mod to the corresponding commit id.

refactor: part 2 of distinguish between Unique and UniqueIndex

---

callbacks/helper_test.go

Adds unit tests for ConvertSliceOfMapToValuesForCreate function in GORM, ensuring correct value conversion from slice of  maps to database columns for CREATE operations.

Add unittest test helper function ConvertSliceOfMapToValuesForCreate

---

clause/where.go
clause/where_test.go
tests/query_test.go

Fix #6845
Address a regression introduced in Gorm v1.25.6, specifically in commit 940358e.
The behavior of the `db.Not` method when used with multiple `Where` conditions has changed unexpectedly. Prior to v1.25.6, the query `db.Not(db.Where("a=1").Where("b=1"))` would correctly translate to SQL as `NOT (a=1 AND b=1)`. However, after the specified commit, the same query started translating to `(NOT a=1 AND NOT b=1)`, which is a significant alteration in the logic.
This PR reverts the `db.Not` method's behavior back to its original state when *gorm.DB passed as arguments.

Fix regression in db.Not introduced in v1.25.6.

---

tests/table_test.go

test for https://github.com/go-gorm/postgres/pull/258

test: namer identifier lenght

---

scan.go

reflect.MakeSlice can only initialize slices

fix(scan.go): reflect.MakeSlice may pass in the wrong type reflect.Array

---

callbacks/preload.go
tests/preload_test.go

When query with nested preload and nested join, the `preloadEntryPoint` ignored the slice type, so it panic.
See and close #6834 
```
DB.Joins("Update.Repo").Joins("Update").Preload("Update.DispatchRecords").Find(&deviceUpdates)
```

fix: nested preload with join panic when find

---

scan.go
tests/query_test.go

If you do not set a zero value, the number of queries is less than the length of the array, and the old value will be used

fix(scan): array element is set to a zero value

---

callbacks/create.go
callbacks/update.go
schema/field.go

chore: optimize conversion of nanoseconds to milliseconds

---

logger/sql.go
logger/sql_test.go

ref: https://github.com/go-gorm/gorm/issues/6898
The wrong sql printed to the terminal can be confusing when use `type XXX int`, so fix it.
```go
type UserStatus int
const (
Normal UserStatus = 1
Forbid UserStatus = 2
)
DB.Where("status = ?", Normal).Find(&users)
```
It print: 
``` go
SELECT * FROM `users` WHERE status = '1' AND `users`.`deleted_at` IS NULL
```
The expected print is: 
``` go 
SELECT * FROM `users` WHERE status = 1 AND `users`.`deleted_at` IS NULL
```

fix: 'type XXXX int' will print wrong sql to terminal

---

callbacks.go
tests/callbacks_test.go

ref: https://github.com/go-gorm/gorm/pull/6910#pullrequestreview-1945116356
Modified the `Remove()` method so that it not only sets the removed flag but also removes the `callback` from the `callbacks` within `compile()`. 
This resolves the following issues:
- The problem where the `Get()` method could retrieve callbacks that have already been removed.
- The problem where removed callbacks could still operate due to the `Remove()` method.
In addition, I have made some modifications to the existing tests.
Previously, the specified `before` and `after` for a `callback` continued to affect the overall order even after being `Remove()`d. I believe that continuing to have an effect after being removed is an unintended behavior.
What do you think? I would appreciate any advice.
If a callback …

fix: remove `callback` from `callbacks` if `Remove()` called

---

callbacks/preload.go
schema/field.go
schema/relationship.go
schema/relationship_test.go
tests/preload_test.go

When using an anonymous mixin struct, preload will request the same sql twice. This behavior contradicts the statement in the document:
The behavior was as expected before this PR was merged: https://github.com/go-gorm/gorm/pull/6137
This PR aims to fix this issue.
```go
package main
import (
"testing"
"gorm.io/gorm"
"gorm.io/gorm/clause"
)
gorm.Model
Age       uint
}
type UserMixin struct {
UserID uint
User User `gorm:"foreignKey:UserID"`
}
type Company struct {
gorm.Model
UserMixin
ID   int
Name string
}
func TestGORM(t *testing.T) {
user := User{Name: "jinzhu"}
DB.Create(&user)
company := Company{Name: "jinzhu's company", UserMixin: UserMixin{UserID: user.ID}}
DB.Create(&company)
var companyResult Company
if err := …
```

fix: duplicated preload

---

chainable_api.go

The pull request adds a descriptive comment for the Unscoped() method in the GORM codebase. This comment explains the functionality of the method, including its purpose, how it overrides soft deletion behavior, and provides an example of its usage.

Added comment describing Unscoped() method

---

utils/utils.go

Faster `utils.FileWithLineNum`. Avoid call `runtime.Caller` multi times.
Trace log performace gained a little.

Faster utils.FileWithLineNum

---

errors.go

Add new error for "Check Constraint Violation"
I added a check constraint in my table in PostgreSQL such as: 
`CONSTRAINT path_check CHECK (path ~ '^/[a-zA-Z0-9\-]+$')`
When an error occurs when I try to add a new row to the table, I want to be sure that it is a rule violation error or another type of error.
```go
if errors.Is(result.Error, gorm.ErrCheckConstraintViolated) {
// handle check constraint violation error
}
```
Pull request for [go-gorm/postgres](https://github.com/go-gorm/postgres): https://github.com/go-gorm/postgres/pull/271

Add new error for "Violation Check Constraint"

---

migrator/migrator.go

Fix panic bug in migrator due to lack of nil check for stmt.Schema
If a series of methods such as HasColumn use strings as table names, it will result in the inability to obtain stmt and cause painc. This modification can prevent painc and use the string passed in by the user as a specific name

Fix panic bug in migrator due to lack of nil check for stmt.Schema

---

scan.go

When using the go clickhouse driver, scanning into sql.RawBytes is not supported for most columns. I think the database/sql standard only [guarantees](https://pkg.go.dev/database/sql#Rows.Scan) that all columns can be converted to *interface{}, not RawBytes, so gorm should not make this assumption.
This issue doesn't affect most drivers like sqlite, mysql, postgres, but it does affect clickhouse. The following test will pass once this change is merged: https://github.com/go-gorm/clickhouse/pull/128

Fix handling of unknown column types

---

go.mod
go.sum
schema/naming.go
schema/relationship.go

change using library strings.Title to cases.Title because of strings. Title is deprecated for Go 1.18
below is a warnings when I run golangci-cli:
```
strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead.
``` 
I rewrite strings.Title -> cases.Title.
cases.TItle returns a Caser so it needed to parse to string because strings.Title returns string
cases.Title can be taken language, but I don't know which language supports for gorm so I tried to write `language.Und`.
this means you didn't decide which language.

fix: strings.Title -> cases.Title bcs strings.Title library is deprecated

---

callbacks/preload.go
tests/preload_test.go

This PR fixes issue #6956.
It adds `reflect.Pointer` as an valid reflect target for preloads.
This seems to be required for preloads of nested optional joins with preload targets.
I am not 100% sure of the broader implications of this change. But the implementation before #6877 also allowed this usecase.
We have complex queries with nested joins and preloads that worked on version 1.25.5 but do not work with the current version.

fix: `unsupported data` on nested joins with preloads

---

association.go
tests/associations_has_many_test.go
tests/associations_has_one_test.go

While replacing associations using an example from the docs panic occurs.
```
db.Model(&user).Association("Languages").Replace(Language{Name: "DE"}, languageEN)
```
This PR fixes this issue by asserting if the value addressable and checking for the association error later.
Here is the PR for the playground example: https://github.com/go-gorm/playground/pull/734
This is not the obvious case, but the code should not panic in the case but handle the invalid value gracefully

Fix association replace non-addressable panic

---

callbacks/preload.go
schema/schema.go
tests/go.mod
tests/joins_test.go

attempt to fix issue https://github.com/go-gorm/gorm/issues/7013
Joins Preload causes panic for a large (>20) number of items, see the issue.
@a631807682 I've tried this since I guess it's better to have a slice with the proper len and cap (if we know it when making the slice) instead of appending items to it. However I'm not very comfortable with the `preload` func and could not figure out which len and cap values to use for the other `schema.MakeSlice` calls. 
Also, can you tell me where I could add a test case for that? Something that would look like the playground test I guess. maybe `joins_test.go` ?

fix: use reflect.Append when preloading nested associations instead of making a slice with fixed size

---

scan.go
tests/scan_test.go

Accidentally closed #6938 so this is the same PR just with the final implemented solution
Addresses #6819
Adding a condition to reset the values of a struct when a scan is initialized to handle nil values from the database
It fixes the example from the docs where you initialize the var once:
```golang
var datasetRow T
for rows.Next() {
err := db.ScanRows(rows, &datasetRow)
```

fix(scan): update Scan function to reset structs to zero values for each scan

---

gorm.go
tests/hooks_test.go

This PR adds `PropagateUnscoped` to `DB`'s `Config`. Its purpose is to allow propagation of the parent `Statement`'s `Unscoped` flag to nested statements. 
Is there any scenario where `getInstance()` where we don't want this flag to propagate? For the record, all tests pass if we just persist the `Unscoped` state when `clone == 1`. 
I just didn't want to introduce what may be a breaking change in more complex production environments for which gorm's tests don't offer coverage therefore this is a disabled by default flag.
Regardless, this kind of change should not be introduced without a flag to panic control it.
When one wants to create advanced hooks which leverage not just the usual Before/After but also `StatementModifier` hooks while reusing the `Unscoped` state of the parent …

add DB level propagation for the Unscoped flag

---

.github/workflows/tests.yml

This pull request updates the GitHub Actions workflow configuration to extend the test matrix for PostgreSQL versions. Specifically, it adds PostgreSQL 14 and PostgreSQL 15 to the list of database versions used in the CI tests. This change ensures that the project is tested against the latest PostgreSQL versions, improving compatibility and stability for users who are using or planning to use these newer versions.

ci: Add PostgreSQL 14 and 15 to GitHub Actions matrix

---

prepare_stmt.go
tests/prepared_stmt_test.go

Fix the issue #7137 
Just fix the memory leaks.

fix memory leaks in PrepareStatementDB

---

tests/compose.yml

This pull request did the following
The file name `compose.yml` is preferred.
https://docs.docker.com/compose/compose-application-model/#the-compose-file
Version top-level element is obsoleted.
https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element-obsolete
When run test, system shows warning.
```sh
tests % ./tests_all.sh
WARN[0000] /Users/john/gorm/tests/docker-compose.yml: `version` is obsolete
...
```
The recommended command-line syntax is `docker compose`.
https://docs.docker.com/compose/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2
`docker-compose start` => `docker compose start`
`docker-compose up` => `docker compose up`

feat: Modernize Docker Compose File

---

.github/workflows/tests.yml
tests/compose.yml
tests/tests_all.sh
tests/tests_test.go

- [*] Do only one thing
- [*] Non breaking API changes
- [*] Tested
This replaces the community SQL Server docker image (https://hub.docker.com/r/mcmoe/mssqldocker) with the official one (https://hub.docker.com/r/microsoft/mssql-server). 
This is an attempt to fix the failing SQL Server workflow in GitHub actions (example [here](https://github.com/go-gorm/gorm/actions/runs/11011610296/job/30576079877#step:2:117)).

Use official SQL Server docker image for tests

---

gorm.go

- test if the dummyDialector has no `Translate()`, occur warning log. (in `TestDialectorWithErrorTranslatorSupport()`)
If the user's config conficts with db driver's dialector implementation, a warning log will be generate to heldy identify the issue.
I enable `TranslateError` config as true, but my MySQL DB driver (version:1.4.7) doesn't implement `Transalte()` method.
Therefore, I had trouble identifying this situation. I think log information is necessary.

refactor: improve logging for unimplemented ErrorTranslator in TranlateError config enabled

---

schema/index.go
schema/index_test.go

- [ X] Do only one thing
- [ X] Non breaking API changes
- [ X] Tested
Changing the implementation of `schema.LookIndex` to use map's two-value assignment tests for the existence of a key when looking for an index before switching to field lookup for performance.
The existing implementation of `Schema.LookIndex` uses linear search (in the best case) instead of using map test using const-time before falling back to a linear scan.
The new implementation has a performance advantage for cases with many indexes.

use map look-up for indexes

---

schema/index.go
schema/index_test.go

Change ParseIndexes to return a list of indices rather than a map, so the callers will iterate in deterministic order.  This means when re-creating a database from the same schema, indexes will be created in a consistent order.
Issue: We observed that, when creating a database based on the same gORM schema multiple times, indexes could appear in different orders, hurting determinism for use-cases like schema comparison.

fix: deterministic index ordering when migrating

---

schema/index.go

Capitalize the priority field of IndexOption so that other systems can access this field from outside the package

feat:Capitalize the priority field of IndexOption（https://github.com/go-gorm/gorm/issues/7331）

---

clause/returning.go
clause/returning_test.go

This pull request fixes the merging behavior of two `clause.Returning` clauses. Specifically, it ensures that if a `clause.Returning` contains expressions without `Columns`, it won't be overridden by specific columns during the merge. This addresses an issue caused by the implicit behavior of empty `clause.Returning` clauses.
I work with queries involving multiple embedded models, where each model requires different columns to be returned. Some operations need all columns to be returned, while others need a subset.
Currently, the merging strategy overrides an implicit empty `clause.Returning` clause with specific columns, making it impossible to implement this mechanism. This fix resolves that limitation, enabling better control over the returned columns in complex query scenarios.

Fixed Empty Returning Clause Merge Edge Case

---

schema/relationship.go

Fixes `fatal error: concurrent map writes` error (https://github.com/go-gorm/gorm/issues/7297)
Using normalized tables

Fix concurrent map writes #7297

---

callbacks/associations.go
scan.go
schema/field.go
schema/utils.go

Fixed deprecated usage of `reflect.PtrTo` and replaced it with `reflect.PointerTo` for slice creation.
This fix addresses a deprecation warning related to `reflect.PtrTo`, ensuring compatibility with the latest Go versions. The change prevents potential issues with reflect-based model handling and improves maintainability.

fix deprecated reflect.PtrTo reflect.PointerTo usage

---

internal/stmt_store/stmt_store.go

Refs: #7435
Fix int type variable `defaultMaxSize` overflows in 32-bit environment.
```shell
GOARCH=386 go test -timeout 20m -v ./...
shell: /usr/bin/bash -e {0}
Error: 
../../../go/pkg/mod/gorm.io/gorm@v1.26.0/internal/stmt_store/stmt_store.go:99:10: 
cannot use defaultMaxSize (untyped int constant 9223372036854775807) as int value in assignment (overflows)
```

fix: int type variable defaultMaxSize overflows in 32-bit environment

---

callbacks/preload.go

Replaced strings.SplitN with strings.Cut to reduce allocations and improve performance.  
Below is my local test code.  
join_test.go  
```go
package gorm
import (
"strings"
"testing"
)
func original(join string) (join0, join1 string, cut bool) {
joins := strings.SplitN(join, ".", 2)
if len(joins) == 2 {
return joins[0], joins[1], true
}
return "", "", false
}
func optimized(join string) (join0, join1 string, cut bool) {
join0, join1, cut = strings.Cut(join, ".")
if cut {
return join0, join1, cut
}
return "", "", false
}
func Benchmark_join(b *testing.B) {
join := "a.b"
b.Run("original", func(b *testing.B) {
b.ReportAllocs()
for i := 0; i < b.N; i++ {
original(join)
}
})
b.Run("optimized", func(b *testing.B) {
b.ReportAllocs()
for i := 0; i < b.N; i++ {
optimized(join)
}
})
}
``` …

perf: use strings.Cut to replace strings.SplitN

---

schema/index.go
schema/relationship.go

`strings.IndexByte` offers better performance than `strings.Index`.

perf: use strings.IndexByte to replace strings.Index

---

schema/relationship.go

feat: error message show field name

---

gorm.go

fix: return init dialector error

---

.github/workflows/tests.yml

- Update MySQL test matrix to use official Docker images
- Add MySQL 9.0 and 8.4 to CI tests
- Replace `mysql/mysql-server:latest` with `mysql:8.0` for consistency with official images
- Add MySQL 9.0 (latest) and 8.4 to ensure compatibility with newer versions
- Keep MySQL 5.7 for backward compatibility testing

test: update MySQL test matrix to use official images and add 9.0, 8.4 versions

---

migrator/migrator.go
tests/go.mod
tests/migrate_test.go

修复automigrate无法正确识别decimal精度是否变化的问题。
[参考issues 7449](https://github.com/go-gorm/gorm/issues/7449)
如果有一个对象如下：
```
type Change struct {
RecID int64  `gorm:"column:recid;type:decimal(9,0);not null" json:"recid"`
}
```
每次自动同步都会触发
```
ALTER TABLE `changes` MODIFY COLUMN `recid` decimal(9,0) NOT NULL    
```

fix decimal migrate error.

---

schema/field.go
tests/check_subset_model_change_test.go

it fixes #7486. a subset of struct of the main model when passed through to update would create an error in the tx.Statement.Changed() function. this PR fixed this problem
below is a example code which demonstrates that condition
struct used for the reference
type Man struct {
Id string
Age string
Name string
Detail string
}
The problem was that if a complete man struct gorm can predict which the column by column index but if a shorter subset of the struct is passed for quick changes then the index of the column lets say Age will not equate to the index in the struct.
fixed issue of #7486

fixes #7486

---

statement.go
tests/query_test.go

Fix a bug I found.
* When there is only one `OR` clause inside a where clause, we want ignore the `OR` condition and just make it `AND`. 
However,  current implementation didn't check  when actually there are multi expressions inside `OR` condition,  these expressions are not expected to be modified to `AND`.
Check the demo below.
```go
package main
import (
"fmt"
"gorm.io/driver/sqlite"
"gorm.io/gorm"
"gorm.io/gorm/clause"
)
ID   uint
Name string
Age  int
}
func main() {
db, _ := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
db.AutoMigrate(&User{})
// insert data
db.Create(&User{Name: "Alice", Age: 30})
db.Create(&User{Name: "Bob", Age: 25})
sub := db.Clauses(clause.Where{
Exprs: []clause.Expression{
clause.OrConditions{
Exprs: []clause.Expression{ …
```

Fix: Unexpected OR Conditions force converted to AND

---

callbacks.go
finisher_api.go
gorm.go
tests/go.mod

Add DefaultContextTimeout option

---

generics.go
schema/schema_helper_test.go
schema/schema_test.go

Fixes warning like this:
assignment copies lock value to relationships:
gorm.io/gorm/schema.Relationships contains sync.RWMutex

avoid copying structures with embedded mutexs
